import React, { useEffect, useState } from 'react'
import { Copy, Eye, EyeOff, ImageOff, Lock, Paintbrush, Save, Trash2, Unlock } from 'lucide-react'
import { useEditorStore } from './store'
import type { BuilderBlock, Device, SourceType } from './types'

const POPULAR_FONTS = ['Inter','Poppins','Roboto','Open Sans','Montserrat','Lato','Nunito','DM Sans','Work Sans','Rubik','Raleway','Quicksand','Source Sans 3','Archivo','PT Sans','Ubuntu','Merriweather','Lora','Playfair Display','Libre Baskerville','Cormorant Garamond','Bebas Neue','Oswald','Anton','Pacifico','Dancing Script','Great Vibes','Lobster']
const fileToDataUrl = (file: File) => new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=reject;r.readAsDataURL(file)})
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="property-section"><h4>{title}</h4>{children}</section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="property-field"><span>{label}</span>{children}</label>}
function TextField({label,value,onChange,multiline=false,placeholder=''}:{label:string;value?:string;onChange:(v:string)=>void;multiline?:boolean;placeholder?:string}){return <Field label={label}>{multiline?<textarea value={value||''} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>:<input value={value||''} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>}</Field>}
function NumberField({label,value,onChange,min=-9999,max=9999,suffix}:{label:string;value?:number;onChange:(v:number)=>void;min?:number;max?:number;suffix?:string}){return <Field label={label}><div className="number-field"><input type="number" min={min} max={max} value={value??0} onChange={e=>onChange(Math.max(min,Math.min(max,Number(e.target.value)||0)))}/>{suffix?<span>{suffix}</span>:null}</div></Field>}
function ColorField({label,value,onChange}:{label:string;value?:string;onChange:(v:string)=>void}){const safe=/^#[0-9A-Fa-f]{6}$/.test(value||'')?value!:'#FFFFFF';return <Field label={label}><div className="color-field"><input type="color" value={safe} onChange={e=>onChange(e.target.value)}/><input value={value||''} onChange={e=>onChange(e.target.value)}/></div></Field>}
function FontField({label,value,onChange,allowInherit=false}:{label:string;value?:string;onChange:(v:string)=>void;allowInherit?:boolean}){return <Field label={label}><select className="property-font-select" value={value||''} onChange={e=>onChange(e.target.value)} style={{fontFamily:value||'inherit'}}>{allowInherit?<option value="">Herdar fonte global</option>:null}{POPULAR_FONTS.map(f=><option key={f} value={f} style={{fontFamily:f}}>{f}</option>)}</select></Field>}
function UploadField({label,value,onChange}:{label:string;value?:string;onChange:(v:string)=>void}){return <Field label={label}><div className="upload-field">{value?<img src={value} alt="Prévia"/>:<div className="upload-empty">Sem arquivo</div>}<div><label className="small-upload">Escolher arquivo<input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f)onChange(await fileToDataUrl(f))}}/></label>{value?<button type="button" className="danger-link" onClick={()=>onChange('')}><ImageOff size={14}/> Remover</button>:null}</div></div></Field>}

function PartTypography({block,prop,label}:{block:BuilderBlock;prop:'titleStyle'|'subtitleStyle'|'textStyle'|'ctaStyle';label:string}){
  const updateProps=useEditorStore(s=>s.updateBlockProps); const current=(block.props[prop]||{}) as Record<string,unknown>
  const set=(patch:Record<string,unknown>)=>updateProps(block.id,{[prop]:{...current,...patch}},`${label} alterado`)
  return <Section title={label}><FontField label="Fonte" value={String(current.fontFamily||'')} allowInherit onChange={v=>set({fontFamily:v||undefined})}/><NumberField label="Tamanho" value={Number(current.fontSize||0)} min={0} max={160} suffix="px" onChange={v=>set({fontSize:v||undefined})}/><ColorField label="Cor" value={String(current.color||'#172230')} onChange={v=>set({color:v})}/><NumberField label="Peso" value={Number(current.fontWeight||400)} min={100} max={900} onChange={v=>set({fontWeight:v})}/><Field label="Alinhamento"><select value={String(current.textAlign||'left')} onChange={e=>set({textAlign:e.target.value})}><option value="left">Esquerda</option><option value="center">Centro</option><option value="right">Direita</option></select></Field></Section>
}

function ContentFields({block}:{block:BuilderBlock}){
  const updateProps=useEditorStore(s=>s.updateBlockProps); const set=(p:Record<string,unknown>,l='Conteúdo alterado')=>updateProps(block.id,p,l); const source=String(block.props.source||'featured') as SourceType
  return <>
    {block.type==='search'?<><TextField label="Placeholder" value={String(block.props.placeholder||'')} onChange={v=>set({placeholder:v})}/><Field label="Mostrar ícone"><input type="checkbox" checked={Boolean(block.props.showIcon??true)} onChange={e=>set({showIcon:e.target.checked})}/></Field></>:null}
    {['hero','banner','card','showcase','promotion','category','brand','distribution','form'].includes(block.type)?<TextField label="Título" value={String(block.props.title||'')} onChange={v=>set({title:v},'Título alterado')}/>:null}
    {['hero','banner'].includes(block.type)?<TextField label="Subtítulo" value={String(block.props.subtitle||'')} multiline onChange={v=>set({subtitle:v})}/>:null}
    {block.type==='hero'?<TextField label="Selo superior" value={String(block.props.eyebrow||'')} onChange={v=>set({eyebrow:v})}/>:null}
    {block.type==='card'?<TextField label="Descrição" value={String(block.props.text||'')} multiline onChange={v=>set({text:v})}/>:null}
    {block.type==='text'?<><Field label="Tipo"><select value={String(block.props.tag||'p')} onChange={e=>set({tag:e.target.value})}><option value="p">Parágrafo</option><option value="h1">Título H1</option><option value="h2">Título H2</option><option value="h3">Título H3</option></select></Field><TextField label="Texto" value={String(block.props.text||'')} multiline onChange={v=>set({text:v})}/></>:null}
    {['hero','banner'].includes(block.type)?<><TextField label="Texto do CTA" value={String(block.props.ctaLabel||'')} onChange={v=>set({ctaLabel:v})}/><TextField label="Link do CTA" value={String(block.props.ctaLink||'')} onChange={v=>set({ctaLink:v})}/></>:null}
    {block.type==='button'?<><TextField label="Texto" value={String(block.props.label||'')} onChange={v=>set({label:v})}/><TextField label="Link" value={String(block.props.link||'')} onChange={v=>set({link:v})}/></>:null}
    {['hero','banner','card'].includes(block.type)?<UploadField label="Imagem" value={String(block.props.image||'')} onChange={v=>set({image:v})}/>:null}
    {block.type==='image'?<UploadField label="Imagem" value={String(block.props.src||'')} onChange={v=>set({src:v})}/>:null}
    {block.type==='header'?<><Field label="Pesquisa antiga no header"><input type="checkbox" checked={Boolean(block.props.showSearch)} onChange={e=>set({showSearch:e.target.checked})}/></Field><p className="layout-help">Recomendado: desligue esta opção e use o elemento independente “Barra de Pesquisa”.</p><Field label="Navegação"><input type="checkbox" checked={Boolean(block.props.showNav)} onChange={e=>set({showNav:e.target.checked})}/></Field></>:null}
    {['showcase','promotion','category','brand','distribution'].includes(block.type)?<><Field label="Origem"><select value={source} onChange={e=>set({source:e.target.value})}><option value="manual">Manual</option><option value="category">Categoria</option><option value="brand">Marca</option><option value="distribution">Distribuição</option><option value="promotion">Promoção</option><option value="mostViewed">Mais vistos</option><option value="mostSearched">Mais pesquisados</option><option value="newest">Recentes</option><option value="featured">Destaques</option></select></Field><NumberField label="Limite" value={Number(block.props.limit||8)} min={1} max={48} onChange={v=>set({limit:v})}/></>:null}
  </>
}

function BlockPanel({block,device}:{block:BuilderBlock;device:Device}){
  const updateBlock=useEditorStore(s=>s.updateBlock); const updateStyle=useEditorStore(s=>s.updateBlockStyle); const updateD=useEditorStore(s=>s.updateDeviceStyle)
  const duplicate=useEditorStore(s=>s.duplicateBlock); const remove=useEditorStore(s=>s.deleteBlock); const toggleHidden=useEditorStore(s=>s.toggleHidden); const toggleLocked=useEditorStore(s=>s.toggleLocked); const copyStyle=useEditorStore(s=>s.copyStyle); const pasteStyle=useEditorStore(s=>s.pasteStyle); const saveAsTemplate=useEditorStore(s=>s.saveAsTemplate)
  const d=block.style[device]||{}; const setD=(p:Record<string,unknown>,l='Layout alterado')=>updateD(block.id,device,p,l)
  return <div className="property-panel-content">
    <div className="selected-block-head"><div><span>{block.type}</span><h3>{block.name}</h3></div></div>
    <div className="quick-actions"><button onClick={()=>duplicate(block.id)}><Copy size={15}/></button><button onClick={()=>toggleHidden(block.id)}>{block.hidden?<Eye size={15}/>:<EyeOff size={15}/>}</button><button onClick={()=>toggleLocked(block.id)}>{block.locked?<Unlock size={15}/>:<Lock size={15}/>}</button><button onClick={()=>copyStyle(block.id)}><Paintbrush size={15}/></button><button onClick={()=>pasteStyle(block.id)}><Save size={15}/></button><button onClick={()=>saveAsTemplate(block.id,block.name)}>TPL</button><button className="danger" onClick={()=>remove(block.id)}><Trash2 size={15}/></button></div>
    <Section title="Conteúdo deste elemento"><ContentFields block={block}/></Section>
    {['hero','banner','card'].includes(block.type)?<PartTypography block={block} prop="titleStyle" label="Título deste elemento"/>:null}
    {['hero','banner'].includes(block.type)?<PartTypography block={block} prop="subtitleStyle" label="Subtítulo deste elemento"/>:null}
    {block.type==='card'?<PartTypography block={block} prop="textStyle" label="Descrição deste card"/>:null}
    {['hero','banner'].includes(block.type)?<PartTypography block={block} prop="ctaStyle" label="CTA deste elemento"/>:null}
    <Section title="Tipografia do elemento"><FontField label="Fonte" value={block.style.fontFamily||''} allowInherit onChange={v=>updateStyle(block.id,{fontFamily:v||undefined})}/><ColorField label="Cor" value={block.style.color} onChange={v=>updateStyle(block.id,{color:v})}/><NumberField label={`Tamanho · ${device}`} value={d.fontSize||16} min={8} max={160} suffix="px" onChange={v=>setD({fontSize:v})}/><NumberField label="Peso" value={block.style.fontWeight||400} min={100} max={900} onChange={v=>updateStyle(block.id,{fontWeight:v})}/><NumberField label="Line-height" value={block.style.lineHeight||1.4} min={0} max={4} onChange={v=>updateStyle(block.id,{lineHeight:v})}/><NumberField label="Letter spacing" value={block.style.letterSpacing||0} min={-10} max={30} suffix="px" onChange={v=>updateStyle(block.id,{letterSpacing:v})}/></Section>
    <Section title={`Posição e tamanho · ${device}`}><Field label="Modo"><select value={d.positionMode||'flow'} onChange={e=>setD({positionMode:e.target.value},e.target.value==='free'?'Modo livre ativado':'Fluxo estruturado ativado')}><option value="flow">Fluxo estruturado</option><option value="free">Modo livre</option></select></Field><div className="layout-preset-row">{['auto','25%','33%','50%','66%','75%','100%'].map(v=><button key={v} onClick={()=>setD({width:v})}>{v}</button>)}</div><TextField label="Largura" value={d.width||'100%'} onChange={v=>setD({width:v||'auto'})}/><NumberField label="Altura mínima" value={d.minHeight||0} min={0} max={3000} suffix="px" onChange={v=>setD({minHeight:v})}/>{d.positionMode==='free'?<><NumberField label="X" value={d.x||0} min={-2000} max={5000} suffix="px" onChange={v=>setD({x:v})}/><NumberField label="Y" value={d.y||0} min={-2000} max={10000} suffix="px" onChange={v=>setD({y:v})}/><NumberField label="Camada" value={d.zIndex||1} min={0} max={999} onChange={v=>setD({zIndex:v})}/><NumberField label="Rotação" value={d.rotate||0} min={-360} max={360} suffix="°" onChange={v=>setD({rotate:v})}/><p className="layout-help">No Modo Livre, use o botão Mover sobre o elemento para arrastar diretamente no canvas.</p></>:null}</Section>
    <Section title="Aparência deste elemento"><ColorField label="Fundo" value={block.style.background} onChange={v=>updateStyle(block.id,{background:v})}/><TextField label="Gradiente" value={block.style.gradient||''} onChange={v=>updateStyle(block.id,{gradient:v})}/><UploadField label="Imagem de fundo" value={block.style.backgroundImage||''} onChange={v=>updateStyle(block.id,{backgroundImage:v})}/><ColorField label="Borda" value={block.style.borderColor} onChange={v=>updateStyle(block.id,{borderColor:v})}/><NumberField label="Espessura" value={block.style.borderWidth||0} min={0} max={30} suffix="px" onChange={v=>updateStyle(block.id,{borderWidth:v})}/><NumberField label="Radius" value={block.style.borderRadius||0} min={0} max={200} suffix="px" onChange={v=>updateStyle(block.id,{borderRadius:v})}/><TextField label="Sombra" value={block.style.shadow||''} onChange={v=>updateStyle(block.id,{shadow:v})}/></Section>
    <Section title="Visibilidade">{(['desktop','tablet','mobile'] as Device[]).map(t=><Field key={t} label={t}><input type="checkbox" checked={!block.hiddenOn[t]} onChange={e=>updateBlock(block.id,{hiddenOn:{...block.hiddenOn,[t]:!e.target.checked}})}/></Field>)}</Section>
  </div>
}

function PagePanel(){const ds=useEditorStore(s=>s.history.present.designSystem);const update=useEditorStore(s=>s.updateDesignSystem);return <div className="property-panel-content"><h3>Fundo da Página</h3><p className="muted">Você clicou no fundo. Somente opções da página aparecem aqui.</p><Section title="Fundo"><ColorField label="Cor da página" value={ds.pageBackground} onChange={v=>update({pageBackground:v},'Fundo da página alterado')}/></Section><Section title="Design global"><p className="layout-help">Para fontes e tokens globais, abra a aba Design. Nada aqui altera um elemento individual.</p></Section></div>}
function DesignSystemPanel(){const ds=useEditorStore(s=>s.history.present.designSystem);const update=useEditorStore(s=>s.updateDesignSystem);return <div className="property-panel-content"><h3>Design Global</h3><Section title="Tipografia"><FontField label="Fonte principal" value={ds.primaryFont} onChange={v=>update({primaryFont:v})}/><FontField label="Fonte secundária" value={ds.secondaryFont} onChange={v=>update({secondaryFont:v})}/></Section><Section title="Cores globais"><ColorField label="Primária" value={ds.primaryColor} onChange={v=>update({primaryColor:v})}/><ColorField label="Secundária" value={ds.secondaryColor} onChange={v=>update({secondaryColor:v})}/><ColorField label="Destaque" value={ds.accentColor} onChange={v=>update({accentColor:v})}/><ColorField label="Cards" value={ds.cardBackground} onChange={v=>update({cardBackground:v})}/></Section></div>}
function IdentityPanel(){const id=useEditorStore(s=>s.history.present.identity);const update=useEditorStore(s=>s.updateIdentity);return <div className="property-panel-content"><h3>Identidade</h3><Section title="Marca"><TextField label="Nome" value={id.companyName} onChange={v=>update({companyName:v})}/><UploadField label="Logo" value={id.logo} onChange={v=>update({logo:v})}/><UploadField label="Logo mobile" value={id.mobileLogo} onChange={v=>update({mobileLogo:v})}/><UploadField label="Favicon" value={id.favicon} onChange={v=>update({favicon:v})}/></Section></div>}
function ThemePanel(){const t=useEditorStore(s=>s.history.present.theme);const update=useEditorStore(s=>s.updateTheme);const themes=['Padrão','Natal','Black Friday','Carnaval','Dia das Mães','Dia dos Pais','Dia das Crianças','Ano Novo'];return <div className="property-panel-content"><h3>Tema</h3><Section title="Tema da página"><Field label="Tema"><select value={t.name} onChange={e=>update({name:e.target.value})}>{themes.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Ativo"><input type="checkbox" checked={t.enabled} onChange={e=>update({enabled:e.target.checked})}/></Field><NumberField label="Intensidade" value={t.intensity} min={0} max={100} onChange={v=>update({intensity:v})}/></Section></div>}

export function PropertiesPanel(){const selectedId=useEditorStore(s=>s.selectedBlockId);const block=useEditorStore(s=>s.history.present.blocks.find(b=>b.id===s.selectedBlockId));const device=useEditorStore(s=>s.device);const [tab,setTab]=useState<'block'|'design'|'identity'|'theme'>('block');useEffect(()=>{if(selectedId)setTab('block')},[selectedId]);return <aside className="properties-panel"><div className="property-tabs"><button className={tab==='block'?'active':''} onClick={()=>setTab('block')}>{selectedId?'Elemento':'Página'}</button><button className={tab==='design'?'active':''} onClick={()=>setTab('design')}>Design</button><button className={tab==='identity'?'active':''} onClick={()=>setTab('identity')}>Identidade</button><button className={tab==='theme'?'active':''} onClick={()=>setTab('theme')}>Tema</button></div>{tab==='block'?(block?<BlockPanel block={block} device={device}/>:<PagePanel/>):null}{tab==='design'?<DesignSystemPanel/>:null}{tab==='identity'?<IdentityPanel/>:null}{tab==='theme'?<ThemePanel/>:null}</aside>}
