import React, { useEffect, useMemo, useState } from 'react'
import { Copy, Eye, EyeOff, ImageOff, Lock, Paintbrush, Plus, Save, Trash2, Unlock } from 'lucide-react'
import { useEditorStore } from './store'
import type { BlockType, BuilderBlock, Device, SourceType } from './types'
import { defaultCanvas } from './defaults'

const POPULAR_FONTS=['Inter','Poppins','Roboto','Open Sans','Montserrat','Lato','Nunito','DM Sans','Work Sans','Rubik','Raleway','Quicksand','Source Sans 3','Archivo','PT Sans','Ubuntu','Merriweather','Lora','Playfair Display','Libre Baskerville','Cormorant Garamond','Bebas Neue','Oswald','Anton','Pacifico','Dancing Script','Great Vibes','Lobster']
const nestable=new Set<BlockType>(['frame','container','row','column','header','hero','banner','carousel','card','showcase','promotion','category','brand','distribution','footer'])
const composite=new Set<BlockType>(['header','hero','banner','carousel','card','showcase','promotion','category','brand','distribution','footer'])
const freeDefaults:Partial<Record<BlockType,number>>={text:320,button:180,image:340,search:460,card:340,hero:760,banner:680,product:280,video:520,map:520,form:520,faq:520,gallery:620,frame:520,container:640}

const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v))
const fileToDataUrl=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=reject;r.readAsDataURL(file)})
function Section({title,children,help}:{title:string;children:React.ReactNode;help?:string}){return <section className="property-section"><h4>{title}</h4>{help?<p className="section-help">{help}</p>:null}{children}</section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="property-field"><span>{label}</span>{children}</label>}
function ToggleField({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <Field label={label}><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/></Field>}
function TextField({label,value,onChange,multiline=false,placeholder=''}:{label:string;value?:string;onChange:(v:string)=>void;multiline?:boolean;placeholder?:string}){return <Field label={label}>{multiline?<textarea value={value||''} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>:<input value={value||''} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>}</Field>}
function NumberField({label,value,onChange,min=-99999,max=99999,suffix,step=1}:{label:string;value?:number;onChange:(v:number)=>void;min?:number;max?:number;suffix?:string;step?:number}){return <Field label={label}><div className="number-field"><input type="number" min={min} max={max} step={step} value={value??0} onChange={e=>onChange(Math.max(min,Math.min(max,Number(e.target.value)||0)))}/>{suffix?<span>{suffix}</span>:null}</div></Field>}
function ColorField({label,value,onChange}:{label:string;value?:string;onChange:(v:string)=>void}){const safe=/^#[0-9A-Fa-f]{6}$/.test(value||'')?value!:'#FFFFFF';return <Field label={label}><div className="color-field"><input type="color" value={safe} onChange={e=>onChange(e.target.value)}/><input value={value||''} onChange={e=>onChange(e.target.value)} placeholder="#RRGGBB"/></div></Field>}
function FontField({label,value,onChange,allowInherit=false}:{label:string;value?:string;onChange:(v:string)=>void;allowInherit?:boolean}){return <Field label={label}><select className="property-font-select" value={value||''} onChange={e=>onChange(e.target.value)} style={{fontFamily:value||'inherit'}}>{allowInherit?<option value="">Herdar fonte global</option>:null}{POPULAR_FONTS.map(f=><option key={f} value={f} style={{fontFamily:f}}>{f}</option>)}</select></Field>}
function UploadField({label,value,onChange}:{label:string;value?:string;onChange:(v:string)=>void}){return <Field label={label}><div className="upload-field">{value?<img src={value} alt="Prévia"/>:<div className="upload-empty">Sem arquivo</div>}<div><label className="small-upload">Escolher arquivo<input type="file" accept="image/*" onChange={async e=>{const f=e.target.files?.[0];if(f)onChange(await fileToDataUrl(f))}}/></label>{value?<button type="button" className="danger-link" onClick={()=>onChange('')}><ImageOff size={14}/>Remover</button>:null}</div></div></Field>}

function commitCanvas(patch:Record<string,unknown>,label:string){
  const state=useEditorStore.getState(),current=state.history.present,next=clone(current)
  const existing=next.canvas||clone(defaultCanvas)
  next.canvas={...existing,...patch} as typeof existing
  next.status='draft';next.updatedAt=new Date().toISOString()
  useEditorStore.setState({
    history:{past:[...state.history.past,clone(current)].slice(-100),present:next,future:[]},
    sandboxes:state.sandboxes.map(s=>s.id===state.activeSandboxId?{...s,document:clone(next)}:s),
    activity:[{id:`log_${Date.now()}`,at:new Date().toISOString(),action:'UPDATE_PAGE',label},...state.activity].slice(0,200),
  })
}
function commitCanvasDevice(device:Device,patch:Record<string,unknown>,label:string){
  const current=useEditorStore.getState().history.present.canvas||clone(defaultCanvas)
  commitCanvas({[device]:{...current[device],...patch}},label)
}
function clearPage(){
  if(!window.confirm('Limpar todos os elementos desta página? Esta ação entra no histórico e pode ser desfeita.'))return
  const state=useEditorStore.getState(),current=state.history.present,next=clone(current);next.blocks=[];next.status='draft';next.updatedAt=new Date().toISOString()
  useEditorStore.setState({history:{past:[...state.history.past,clone(current)].slice(-100),present:next,future:[]},selectedBlockId:null,sandboxes:state.sandboxes.map(s=>s.id===state.activeSandboxId?{...s,document:clone(next)}:s),activity:[{id:`log_${Date.now()}`,at:new Date().toISOString(),action:'CLEAR_PAGE',label:'Página limpa'},...state.activity].slice(0,200)})
}

function PartTypography({block,prop,label}:{block:BuilderBlock;prop:'titleStyle'|'subtitleStyle'|'textStyle'|'ctaStyle';label:string}){
  const updateProps=useEditorStore(s=>s.updateBlockProps);const current=(block.props[prop]||{}) as Record<string,unknown>;const set=(p:Record<string,unknown>)=>updateProps(block.id,{[prop]:{...current,...p}},`${label} alterado`)
  return <Section title={label}><FontField label="Fonte" value={String(current.fontFamily||'')} allowInherit onChange={v=>set({fontFamily:v||undefined})}/><NumberField label="Tamanho" value={Number(current.fontSize||0)} min={0} max={200} suffix="px" onChange={v=>set({fontSize:v||undefined})}/><ColorField label="Cor" value={String(current.color||'#172230')} onChange={v=>set({color:v})}/><NumberField label="Peso" value={Number(current.fontWeight||400)} min={100} max={900} step={100} onChange={v=>set({fontWeight:v})}/><Field label="Alinhamento"><select value={String(current.textAlign||'left')} onChange={e=>set({textAlign:e.target.value})}><option value="left">Esquerda</option><option value="center">Centro</option><option value="right">Direita</option></select></Field></Section>
}

function ListEditor({items,onChange,label='Item'}:{items:string[];onChange:(items:string[])=>void;label?:string}){
  return <div className="list-editor">{items.map((item,i)=><div className="list-editor-row" key={i}><input value={item} onChange={e=>{const next=[...items];next[i]=e.target.value;onChange(next)}}/><button type="button" onClick={()=>onChange(items.filter((_,x)=>x!==i))}><Trash2 size={13}/></button></div>)}<button type="button" className="add-row-button" onClick={()=>onChange([...items,`${label} ${items.length+1}`])}><Plus size={13}/>Adicionar {label.toLowerCase()}</button></div>
}

function ShowcaseFields({block,device}:{block:BuilderBlock;device:Device}){
  const updateProps=useEditorStore(s=>s.updateBlockProps),updateD=useEditorStore(s=>s.updateDeviceStyle);const set=(p:Record<string,unknown>,l='Vitrine alterada')=>updateProps(block.id,p,l);const source=String(block.props.source||'featured') as SourceType
  return <>
    <TextField label="Título" value={String(block.props.title||'')} onChange={v=>set({title:v})}/>
    <TextField label="Selo/kicker" value={String(block.props.kicker||'')} onChange={v=>set({kicker:v})}/>
    <Field label="Origem"><select value={source} onChange={e=>set({source:e.target.value})}><option value="manual">Manual</option><option value="category">Categoria</option><option value="brand">Marca</option><option value="distribution">Distribuição</option><option value="promotion">Promoção</option><option value="mostViewed">Mais vistos</option><option value="mostSearched">Mais pesquisados</option><option value="newest">Recentes</option><option value="featured">Destaques</option></select></Field>
    {['category','brand','distribution','promotion'].includes(source)?<TextField label="Filtro" value={String(block.props.sourceValue||'')} onChange={v=>set({sourceValue:v})}/>:null}
    <NumberField label="Quantidade de produtos" value={Number(block.props.limit||8)} min={1} max={100} onChange={v=>set({limit:v})}/>
    <ToggleField label="Cabeçalho da vitrine" checked={block.props.showHeader!==false} onChange={v=>set({showHeader:v})}/><ToggleField label="Mostrar kicker" checked={Boolean(block.props.showKicker)} onChange={v=>set({showKicker:v})}/><ToggleField label="Mostrar contador" checked={Boolean(block.props.showCount)} onChange={v=>set({showCount:v})}/>
    <div className="mini-divider">Campos do card</div>
    <ToggleField label="Imagem" checked={block.props.showImage!==false} onChange={v=>set({showImage:v})}/><ToggleField label="Marca" checked={block.props.showBrand!==false} onChange={v=>set({showBrand:v})}/><ToggleField label="Nome" checked={block.props.showName!==false} onChange={v=>set({showName:v})}/><ToggleField label="Breadcrumb" checked={block.props.showBreadcrumb!==false} onChange={v=>set({showBreadcrumb:v})}/><ToggleField label="Preço" checked={Boolean(block.props.showPrice)} onChange={v=>set({showPrice:v})}/><ToggleField label="Botão" checked={block.props.showButton!==false} onChange={v=>set({showButton:v})}/><TextField label="Texto do botão" value={String(block.props.buttonLabel||'Ver informações')} onChange={v=>set({buttonLabel:v})}/>
    <div className="mini-divider">Tamanho dos cards</div>
    <ToggleField label="Ajuste automático por largura" checked={Boolean(block.props.autoFitCards)} onChange={v=>set({autoFitCards:v})}/>
    {Boolean(block.props.autoFitCards)?<NumberField label="Largura mínima do card" value={Number(block.props.cardMinWidth||220)} min={100} max={900} suffix="px" onChange={v=>set({cardMinWidth:v})}/>:<NumberField label={`Colunas · ${device}`} value={block.style[device]?.columns||1} min={1} max={12} onChange={v=>updateD(block.id,device,{columns:v},'Colunas da vitrine alteradas')}/>}<NumberField label="Espaço entre cards" value={Number(block.props.cardGap||16)} min={0} max={120} suffix="px" onChange={v=>set({cardGap:v})}/><NumberField label="Padding do card" value={Number(block.props.cardPadding||14)} min={0} max={100} suffix="px" onChange={v=>set({cardPadding:v})}/><NumberField label="Altura da imagem" value={Number(block.props.imageHeight||170)} min={40} max={800} suffix="px" onChange={v=>set({imageHeight:v})}/><NumberField label="Radius do card" value={Number(block.props.cardRadius||18)} min={0} max={100} suffix="px" onChange={v=>set({cardRadius:v})}/><ColorField label="Fundo do card" value={String(block.props.cardBackground||'#FFFFFF')} onChange={v=>set({cardBackground:v})}/>
  </>
}

function ContentFields({block,device}:{block:BuilderBlock;device:Device}){
  const updateProps=useEditorStore(s=>s.updateBlockProps);const set=(p:Record<string,unknown>,l='Conteúdo alterado')=>updateProps(block.id,p,l)
  if(block.type==='showcase'||block.type==='promotion')return <ShowcaseFields block={block} device={device}/>
  return <>
    {block.type==='search'?<><TextField label="Placeholder" value={String(block.props.placeholder||'')} onChange={v=>set({placeholder:v})}/><ToggleField label="Mostrar ícone" checked={block.props.showIcon!==false} onChange={v=>set({showIcon:v})}/></>:null}
    {block.type==='text'?<><Field label="Tipo"><select value={String(block.props.tag||'p')} onChange={e=>set({tag:e.target.value})}><option value="p">Parágrafo</option><option value="h1">Título H1</option><option value="h2">Título H2</option><option value="h3">Título H3</option></select></Field><TextField label="Texto" value={String(block.props.text||'')} multiline onChange={v=>set({text:v})}/></>:null}
    {block.type==='button'?<><TextField label="Texto" value={String(block.props.label||'')} onChange={v=>set({label:v})}/><TextField label="Link" value={String(block.props.link||'')} onChange={v=>set({link:v})}/><Field label="Abrir em"><select value={String(block.props.target||'_self')} onChange={e=>set({target:e.target.value})}><option value="_self">Mesma aba</option><option value="_blank">Nova aba</option></select></Field></>:null}
    {block.type==='image'?<><UploadField label="Imagem" value={String(block.props.src||'')} onChange={v=>set({src:v})}/><TextField label="Texto alternativo" value={String(block.props.alt||'')} onChange={v=>set({alt:v})}/></>:null}
    {block.type==='product'?<><TextField label="Código do produto" value={String(block.props.productCode||'')} onChange={v=>set({productCode:v})}/><ToggleField label="Imagem" checked={block.props.showImage!==false} onChange={v=>set({showImage:v})}/><ToggleField label="Marca" checked={block.props.showBrand!==false} onChange={v=>set({showBrand:v})}/><ToggleField label="Nome" checked={block.props.showName!==false} onChange={v=>set({showName:v})}/><ToggleField label="Breadcrumb" checked={block.props.showBreadcrumb!==false} onChange={v=>set({showBreadcrumb:v})}/><ToggleField label="Preço" checked={Boolean(block.props.showPrice)} onChange={v=>set({showPrice:v})}/><ToggleField label="Botão" checked={block.props.showButton!==false} onChange={v=>set({showButton:v})}/><TextField label="Texto do botão" value={String(block.props.buttonLabel||'Ver informações')} onChange={v=>set({buttonLabel:v})}/></>:null}
    {['hero','banner','card'].includes(block.type)?<><TextField label="Título" value={String(block.props.title||'')} onChange={v=>set({title:v})}/>{block.type!=='card'?<TextField label="Subtítulo" value={String(block.props.subtitle||'')} multiline onChange={v=>set({subtitle:v})}/>:<TextField label="Descrição" value={String(block.props.text||'')} multiline onChange={v=>set({text:v})}/>}<UploadField label="Imagem" value={String(block.props.image||'')} onChange={v=>set({image:v})}/>{block.type!=='card'?<><TextField label="Texto do CTA" value={String(block.props.ctaLabel||'')} onChange={v=>set({ctaLabel:v})}/><TextField label="Link do CTA" value={String(block.props.ctaLink||'')} onChange={v=>set({ctaLink:v})}/></>:null}</>:null}
    {block.type==='header'?<><ToggleField label="Logo/nome padrão" checked={block.props.showDefaultContent!==false} onChange={v=>set({showDefaultContent:v})}/><ToggleField label="Navegação padrão" checked={Boolean(block.props.showNav)} onChange={v=>set({showNav:v})}/><ToggleField label="Pesquisa antiga no header" checked={Boolean(block.props.showSearch)} onChange={v=>set({showSearch:v})}/></>:null}
    {block.type==='footer'?<TextField label="Texto institucional" value={String(block.props.text||'')} onChange={v=>set({text:v})}/>:null}
    {block.type==='carousel'?<ListEditor items={(block.props.slides as string[])||[]} label="Slide" onChange={items=>set({slides:items})}/>:null}
    {block.type==='form'?<><TextField label="Título" value={String(block.props.title||'')} onChange={v=>set({title:v})}/><ListEditor items={(block.props.fields as string[])||[]} label="Campo" onChange={items=>set({fields:items})}/><TextField label="Texto do botão" value={String(block.props.submitLabel||'Enviar')} onChange={v=>set({submitLabel:v})}/></>:null}
    {block.type==='map'?<TextField label="Endereço" value={String(block.props.address||'')} onChange={v=>set({address:v})}/>:null}
    {block.type==='video'?<TextField label="URL do vídeo" value={String(block.props.url||'')} onChange={v=>set({url:v})}/>:null}
    {['category','brand','distribution'].includes(block.type)?<TextField label="Título" value={String(block.props.title||'')} onChange={v=>set({title:v})}/>:null}
  </>
}

function ChildComposer({block,device}:{block:BuilderBlock;device:Device}){
  const doc=useEditorStore(s=>s.history.present),add=useEditorStore(s=>s.addBlock),updateD=useEditorStore(s=>s.updateDeviceStyle),select=useEditorStore(s=>s.selectBlock),remove=useEditorStore(s=>s.deleteBlock),updateProps=useEditorStore(s=>s.updateBlockProps)
  const children=doc.blocks.filter(b=>b.parentId===block.id).sort((a,b)=>a.order-b.order)
  const addChild=(type:BlockType)=>{add(type,block.id);const id=useEditorStore.getState().selectedBlockId;if(id){const width=freeDefaults[type]||260;updateD(id,device,{positionMode:'free',width:`${width}px`,x:16+(children.length%4)*16,y:16+(children.length%6)*20,zIndex:children.length+2},'Conteúdo livre adicionado dentro do elemento')}}
  return <Section title="Conteúdo interno livre" help="Adicione elementos independentes dentro deste quadro. Cada filho terá seu próprio painel de edição.">
    {composite.has(block.type)?<ToggleField label="Usar conteúdo pronto deste componente" checked={block.props.showDefaultContent!==false} onChange={v=>updateProps(block.id,{showDefaultContent:v},v?'Conteúdo padrão ativado':'Componente transformado em quadro livre')}/>:null}
    <div className="child-add-grid">{(['text','button','image','search','card','product','frame'] as BlockType[]).map(type=><button type="button" key={type} onClick={()=>addChild(type)}><Plus size={12}/>{type}</button>)}</div>
    {children.length?<div className="child-list">{children.map(child=><div key={child.id}><button type="button" onClick={()=>select(child.id)}>{child.name}</button><button type="button" className="danger-mini" onClick={()=>remove(child.id)}><Trash2 size={12}/></button></div>)}</div>:<p className="layout-help">Nenhum elemento interno. Você pode deixar o componente vazio e montar do zero.</p>}
  </Section>
}

function BlockPanel({block,device}:{block:BuilderBlock;device:Device}){
  const updateBlock=useEditorStore(s=>s.updateBlock),updateStyle=useEditorStore(s=>s.updateBlockStyle),updateD=useEditorStore(s=>s.updateDeviceStyle)
  const duplicate=useEditorStore(s=>s.duplicateBlock),remove=useEditorStore(s=>s.deleteBlock),toggleHidden=useEditorStore(s=>s.toggleHidden),toggleLocked=useEditorStore(s=>s.toggleLocked),copyStyle=useEditorStore(s=>s.copyStyle),pasteStyle=useEditorStore(s=>s.pasteStyle),saveAsTemplate=useEditorStore(s=>s.saveAsTemplate)
  const d=block.style[device]||{},setD=(p:Record<string,unknown>,l='Layout alterado')=>updateD(block.id,device,p,l)
  const activateFree=()=>{const current=String(d.width||'');const width=/px$/.test(current)?current:`${freeDefaults[block.type]||360}px`;setD({positionMode:'free',width,height:d.height||d.minHeight||undefined,x:d.x||24,y:d.y||24,zIndex:d.zIndex||2},'Modo livre ativado')}
  const numericWidth=Number.parseFloat(String(d.width||''))||freeDefaults[block.type]||360
  const numericHeight=Number(d.height||d.minHeight||0)
  return <div className="property-panel-content element-inspector">
    <div className="selected-block-head"><div><span>{block.type}</span><h3>{block.name}</h3></div></div>
    <TextField label="Nome do elemento" value={block.name} onChange={v=>updateBlock(block.id,{name:v||block.type},'Elemento renomeado')}/>
    <div className="quick-actions"><button onClick={()=>duplicate(block.id)} title="Duplicar"><Copy size={15}/></button><button onClick={()=>toggleHidden(block.id)} title="Mostrar/ocultar">{block.hidden?<Eye size={15}/>:<EyeOff size={15}/>}</button><button onClick={()=>toggleLocked(block.id)} title="Bloquear/desbloquear">{block.locked?<Unlock size={15}/>:<Lock size={15}/>}</button><button onClick={()=>copyStyle(block.id)} title="Copiar estilo"><Paintbrush size={15}/></button><button onClick={()=>pasteStyle(block.id)} title="Colar estilo"><Save size={15}/></button><button onClick={()=>saveAsTemplate(block.id,block.name)} title="Salvar template">TPL</button><button className="danger" onClick={()=>remove(block.id)} title="Excluir"><Trash2 size={15}/></button></div>

    <Section title="Conteúdo deste elemento"><ContentFields block={block} device={device}/></Section>
    {nestable.has(block.type)?<ChildComposer block={block} device={device}/>:null}
    {['hero','banner','card'].includes(block.type)?<PartTypography block={block} prop="titleStyle" label="Título interno"/>:null}
    {['hero','banner'].includes(block.type)?<PartTypography block={block} prop="subtitleStyle" label="Subtítulo interno"/>:null}
    {block.type==='card'?<PartTypography block={block} prop="textStyle" label="Descrição interna"/>:null}
    {['hero','banner'].includes(block.type)?<PartTypography block={block} prop="ctaStyle" label="CTA interno"/>:null}

    <Section title="Tipografia deste elemento"><FontField label="Fonte" value={block.style.fontFamily||''} allowInherit onChange={v=>updateStyle(block.id,{fontFamily:v||undefined},'Fonte do elemento alterada')}/><ColorField label="Cor do texto" value={block.style.color} onChange={v=>updateStyle(block.id,{color:v})}/><NumberField label={`Tamanho · ${device}`} value={d.fontSize||16} min={6} max={240} suffix="px" onChange={v=>setD({fontSize:v})}/><NumberField label="Peso" value={block.style.fontWeight||400} min={100} max={900} step={100} onChange={v=>updateStyle(block.id,{fontWeight:v})}/><NumberField label="Line-height" value={block.style.lineHeight||1.4} min={0.5} max={5} step={0.1} onChange={v=>updateStyle(block.id,{lineHeight:v})}/><NumberField label="Letter spacing" value={block.style.letterSpacing||0} min={-20} max={60} suffix="px" onChange={v=>updateStyle(block.id,{letterSpacing:v})}/><Field label="Alinhamento"><select value={d.textAlign||'left'} onChange={e=>setD({textAlign:e.target.value})}><option value="left">Esquerda</option><option value="center">Centro</option><option value="right">Direita</option><option value="justify">Justificado</option></select></Field></Section>

    <Section title={`Posição e tamanho · ${device}`} help="Sem presets de porcentagem. No Modo Livre, arraste e redimensione diretamente no canvas ou digite valores exatos.">
      <Field label="Modo de posicionamento"><div className="segmented-control"><button type="button" className={(d.positionMode||'flow')==='flow'?'active':''} onClick={()=>setD({positionMode:'flow',x:0,y:0},'Fluxo estruturado ativado')}>Estruturado</button><button type="button" className={d.positionMode==='free'?'active':''} onClick={activateFree}>Livre</button></div></Field>
      {d.positionMode==='free'?<><NumberField label="Largura" value={numericWidth} min={24} max={5000} suffix="px" onChange={v=>setD({width:`${v}px`},'Largura exata alterada')}/><NumberField label="Altura" value={numericHeight} min={0} max={10000} suffix="px" onChange={v=>setD({height:v||undefined},'Altura exata alterada')}/><div className="xy-grid"><NumberField label="X" value={d.x||0} min={-5000} max={10000} suffix="px" onChange={v=>setD({x:v})}/><NumberField label="Y" value={d.y||0} min={-5000} max={30000} suffix="px" onChange={v=>setD({y:v})}/></div><NumberField label="Camada (Z)" value={d.zIndex||1} min={0} max={9999} onChange={v=>setD({zIndex:v})}/><NumberField label="Rotação" value={d.rotate||0} min={-360} max={360} suffix="°" onChange={v=>setD({rotate:v})}/></>:<><TextField label="Largura no fluxo" value={String(d.width||'auto')} placeholder="auto, 640px ou 100%" onChange={v=>setD({width:v||'auto'})}/><NumberField label="Altura mínima" value={d.minHeight||0} min={0} max={10000} suffix="px" onChange={v=>setD({minHeight:v})}/><NumberField label="Gap" value={d.gap||0} min={0} max={300} suffix="px" onChange={v=>setD({gap:v})}/><div className="quad-grid"><NumberField label="Margem topo" value={d.marginTop||0} suffix="px" onChange={v=>setD({marginTop:v})}/><NumberField label="Margem esquerda" value={d.marginLeft||0} suffix="px" onChange={v=>setD({marginLeft:v})}/><NumberField label="Padding topo" value={d.paddingTop||0} suffix="px" onChange={v=>setD({paddingTop:v})}/><NumberField label="Padding lateral" value={d.paddingLeft||0} suffix="px" onChange={v=>setD({paddingLeft:v,paddingRight:v})}/></div></>}
    </Section>

    <Section title="Aparência deste elemento"><ColorField label="Fundo" value={block.style.background} onChange={v=>updateStyle(block.id,{background:v},'Fundo do elemento alterado')}/><TextField label="Gradiente" value={block.style.gradient||''} placeholder="linear-gradient(...)" onChange={v=>updateStyle(block.id,{gradient:v})}/><UploadField label="Imagem de fundo" value={block.style.backgroundImage||''} onChange={v=>updateStyle(block.id,{backgroundImage:v})}/><Field label="Tamanho da imagem"><select value={block.style.backgroundSize||'cover'} onChange={e=>updateStyle(block.id,{backgroundSize:e.target.value as 'cover'|'contain'|'auto'})}><option value="cover">Cobrir</option><option value="contain">Conter</option><option value="auto">Original</option></select></Field><ColorField label="Borda" value={block.style.borderColor} onChange={v=>updateStyle(block.id,{borderColor:v})}/><NumberField label="Espessura" value={block.style.borderWidth||0} min={0} max={40} suffix="px" onChange={v=>updateStyle(block.id,{borderWidth:v})}/><NumberField label="Radius" value={block.style.borderRadius||0} min={0} max={300} suffix="px" onChange={v=>updateStyle(block.id,{borderRadius:v})}/><TextField label="Sombra" value={block.style.shadow||''} placeholder="0 12px 32px rgba(...)" onChange={v=>updateStyle(block.id,{shadow:v})}/><NumberField label="Opacidade" value={block.style.opacity??100} min={0} max={100} suffix="%" onChange={v=>updateStyle(block.id,{opacity:v})}/></Section>
    <Section title="Visibilidade">{(['desktop','tablet','mobile'] as Device[]).map(t=><ToggleField key={t} label={t} checked={!block.hiddenOn[t]} onChange={v=>updateBlock(block.id,{hiddenOn:{...block.hiddenOn,[t]:!v}},`Visibilidade ${t} alterada`)}/>)}</Section>
  </div>
}

function PagePanel({device}:{device:Device}){
  const doc=useEditorStore(s=>s.history.present),canvas=doc.canvas||defaultCanvas,ds=doc.designSystem
  const cfg=canvas[device]||defaultCanvas[device]
  return <div className="property-panel-content page-inspector"><h3>Página / Fundo</h3><p className="muted">Somente a página é alterada aqui. Nenhum elemento individual muda.</p>
    <Section title="Fundo da página"><ColorField label="Cor" value={canvas.background||ds.pageBackground} onChange={v=>commitCanvas({background:v,gradient:''},'Cor do fundo alterada')}/><TextField label="Gradiente" value={canvas.gradient||''} placeholder="linear-gradient(...)" onChange={v=>commitCanvas({gradient:v},'Gradiente da página alterado')}/><UploadField label="Imagem de fundo" value={canvas.backgroundImage||''} onChange={v=>commitCanvas({backgroundImage:v},v?'Imagem de fundo aplicada':'Imagem de fundo removida')}/><Field label="Ajuste da imagem"><select value={canvas.backgroundSize||'cover'} onChange={e=>commitCanvas({backgroundSize:e.target.value},'Ajuste do fundo alterado')}><option value="cover">Cobrir</option><option value="contain">Conter</option><option value="auto">Original</option></select></Field><TextField label="Posição" value={canvas.backgroundPosition||'center'} onChange={v=>commitCanvas({backgroundPosition:v},'Posição do fundo alterada')}/></Section>
    <Section title={`Prancheta · ${device}`}><NumberField label="Largura" value={cfg.width} min={280} max={5000} suffix="px" onChange={v=>commitCanvasDevice(device,{width:v},'Largura da prancheta alterada')}/><NumberField label="Altura" value={cfg.height} min={600} max={30000} suffix="px" onChange={v=>commitCanvasDevice(device,{height:v},'Altura da prancheta alterada')}/></Section>
    <Section title="Guias"><ToggleField label="Mostrar grade" checked={Boolean(canvas.showGrid)} onChange={v=>commitCanvas({showGrid:v},'Grade visual alterada')}/><ToggleField label="Encaixar na grade" checked={Boolean(canvas.snapToGrid)} onChange={v=>commitCanvas({snapToGrid:v},'Snap da grade alterado')}/><NumberField label="Tamanho da grade" value={canvas.gridSize||8} min={1} max={100} suffix="px" onChange={v=>commitCanvas({gridSize:v},'Grade alterada')}/></Section>
    <Section title="Página em branco"><button type="button" className="danger-wide" onClick={clearPage}><Trash2 size={14}/>Limpar todos os elementos</button><p className="layout-help">Use quando quiser começar a página totalmente do zero. É possível desfazer com Ctrl+Z.</p></Section>
  </div>
}

function DesignSystemPanel(){const ds=useEditorStore(s=>s.history.present.designSystem),update=useEditorStore(s=>s.updateDesignSystem);return <div className="property-panel-content global-inspector"><h3>Design Global</h3><p className="muted">Tokens globais. Elementos com configuração própria não são forçados a usar estes valores.</p><Section title="Tipografia global"><FontField label="Fonte principal" value={ds.primaryFont} onChange={v=>update({primaryFont:v},'Fonte global principal alterada')}/><FontField label="Fonte secundária" value={ds.secondaryFont} onChange={v=>update({secondaryFont:v},'Fonte global secundária alterada')}/></Section><Section title="Cores globais"><ColorField label="Primária" value={ds.primaryColor} onChange={v=>update({primaryColor:v})}/><ColorField label="Secundária" value={ds.secondaryColor} onChange={v=>update({secondaryColor:v})}/><ColorField label="Destaque" value={ds.accentColor} onChange={v=>update({accentColor:v})}/><ColorField label="Cards" value={ds.cardBackground} onChange={v=>update({cardBackground:v})}/><ColorField label="Bordas" value={ds.borderColor} onChange={v=>update({borderColor:v})}/></Section><Section title="Forma"><NumberField label="Radius padrão de card" value={ds.cardRadius} min={0} max={200} suffix="px" onChange={v=>update({cardRadius:v})}/><NumberField label="Radius padrão de botão" value={ds.buttonRadius} min={0} max={200} suffix="px" onChange={v=>update({buttonRadius:v})}/><TextField label="Sombra padrão" value={ds.shadow} onChange={v=>update({shadow:v})}/></Section></div>}

function IdentityPanel(){const id=useEditorStore(s=>s.history.present.identity),update=useEditorStore(s=>s.updateIdentity);return <div className="property-panel-content identity-inspector"><h3>Identidade Visual</h3><p className="muted">Logo e nome possuem espaço próprio e não podem se sobrepor.</p><Section title="Marca"><TextField label="Nome da empresa" value={id.companyName} onChange={v=>update({companyName:v})}/><ToggleField label="Mostrar nome ao lado da logo" checked={id.showCompanyName!==false} onChange={v=>update({showCompanyName:v})}/><UploadField label="Logo principal" value={id.logo} onChange={v=>update({logo:v})}/><UploadField label="Logo mobile" value={id.mobileLogo} onChange={v=>update({mobileLogo:v})}/></Section><Section title="Tamanho da logo"><NumberField label="Largura máxima" value={id.logoWidth||150} min={24} max={600} suffix="px" onChange={v=>update({logoWidth:v})}/><NumberField label="Altura máxima" value={id.logoHeight||48} min={20} max={240} suffix="px" onChange={v=>update({logoHeight:v})}/><NumberField label="Espaço logo/nome" value={id.brandGap??10} min={0} max={100} suffix="px" onChange={v=>update({brandGap:v})}/></Section><Section title="Outros"><UploadField label="Favicon" value={id.favicon} onChange={v=>update({favicon:v})}/><UploadField label="Ícone PWA" value={id.pwaIcon} onChange={v=>update({pwaIcon:v})}/><UploadField label="Marca d'água" value={id.watermark} onChange={v=>update({watermark:v})}/></Section></div>}

function ThemePanel(){const theme=useEditorStore(s=>s.history.present.theme),update=useEditorStore(s=>s.updateTheme);return <div className="property-panel-content theme-inspector"><h3>Tema</h3><Section title="Tema ativo"><Field label="Preset"><select value={theme.name} onChange={e=>update({name:e.target.value})}>{['Padrão','Natal','Black Friday','Carnaval','Dia das Mães','Dia dos Pais','Dia das Crianças','Ano Novo'].map(t=><option key={t}>{t}</option>)}</select></Field><ToggleField label="Ativo" checked={theme.enabled} onChange={v=>update({enabled:v})}/><ToggleField label="Partículas" checked={theme.particles} onChange={v=>update({particles:v})}/><NumberField label="Intensidade" value={theme.intensity} min={0} max={100} suffix="%" onChange={v=>update({intensity:v})}/><ToggleField label="Animar desktop" checked={theme.animateDesktop} onChange={v=>update({animateDesktop:v})}/><ToggleField label="Animar mobile" checked={theme.animateMobile} onChange={v=>update({animateMobile:v})}/></Section></div>}

export function PropertiesPanel(){
  const selectedId=useEditorStore(s=>s.selectedBlockId),doc=useEditorStore(s=>s.history.present),device=useEditorStore(s=>s.device)
  const block=useMemo(()=>doc.blocks.find(b=>b.id===selectedId)||null,[doc.blocks,selectedId])
  const [tab,setTab]=useState<'element'|'page'|'global'|'identity'|'theme'>(block?'element':'page')
  useEffect(()=>{if(block)setTab('element');else if(tab==='element')setTab('page')},[selectedId])
  return <aside className="properties-panel freedom-properties">
    <div className="property-tabs freedom-tabs">
      <button className={tab==='element'?'active':''} disabled={!block} onClick={()=>block&&setTab('element')}>Elemento</button>
      <button className={tab==='page'?'active':''} onClick={()=>setTab('page')}>Página</button>
      <button className={tab==='global'?'active':''} onClick={()=>setTab('global')}>Global</button>
      <button className={tab==='identity'?'active':''} onClick={()=>setTab('identity')}>Identidade</button>
      <button className={tab==='theme'?'active':''} onClick={()=>setTab('theme')}>Tema</button>
    </div>
    {tab==='element'&&block?<BlockPanel block={block} device={device}/>:null}
    {tab==='element'&&!block?<div className="empty-properties">Selecione um elemento no canvas.</div>:null}
    {tab==='page'?<PagePanel device={device}/>:null}
    {tab==='global'?<DesignSystemPanel/>:null}
    {tab==='identity'?<IdentityPanel/>:null}
    {tab==='theme'?<ThemePanel/>:null}
  </aside>
}
