import React, { useRef } from 'react'
import { Move } from 'lucide-react'
import { useEditorStore } from './store'
import type { BuilderBlock, Device } from './types'

type Axis = 'x' | 'y' | 'xy'
type Props = { block: BuilderBlock; device: Device; children: React.ReactNode }
const minWidthFor=(type:BuilderBlock['type'])=>['button','text','search'].includes(type)?80:120
const minHeightFor=(type:BuilderBlock['type'])=>['button','text','search'].includes(type)?34:56

export function VisualResizeHandles({block,device,children}:Props){
  const shellRef=useRef<HTMLDivElement>(null);const updateDeviceStyle=useEditorStore(s=>s.updateDeviceStyle);const d=block.style[device]||{};const width=d.width||'100%';const free=d.positionMode==='free'
  const startResize=(axis:Axis,event:React.PointerEvent<HTMLButtonElement>)=>{event.preventDefault();event.stopPropagation();const shell=shellRef.current;if(!shell)return;const startX=event.clientX,startY=event.clientY,rect=shell.getBoundingClientRect(),parentWidth=(free?shell.parentElement?.parentElement:shell.parentElement)?.getBoundingClientRect().width||rect.width,startWidth=rect.width,startHeight=rect.height;const move=(p:PointerEvent)=>{const patch:Record<string,unknown>={};if(axis==='x'||axis==='xy')patch.width=`${Math.round(Math.max(minWidthFor(block.type),Math.min(parentWidth,startWidth+p.clientX-startX)))}px`;if(axis==='y'||axis==='xy')patch.minHeight=Math.round(Math.max(minHeightFor(block.type),startHeight+p.clientY-startY));updateDeviceStyle(block.id,device,patch,'Tamanho ajustado visualmente')};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true})}
  const startMove=(event:React.PointerEvent<HTMLButtonElement>)=>{if(!free)return;event.preventDefault();event.stopPropagation();const startX=event.clientX,startY=event.clientY,x=Number(d.x||0),y=Number(d.y||0);const move=(p:PointerEvent)=>updateDeviceStyle(block.id,device,{x:Math.round(x+p.clientX-startX),y:Math.round(y+p.clientY-startY)},'Elemento movido no canvas livre');const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true})}
  const fitWidth=(value:string)=>updateDeviceStyle(block.id,device,{width:value},`Largura ${value}`)
  return <div ref={shellRef} className={`visual-resize-shell ${free?'free-mode':'flow-mode'}`} style={{width:free?'100%':width}} onClick={e=>e.stopPropagation()}><div className="visual-resize-content">{children}</div><div className="visual-size-badge">{width==='auto'?'Auto':width} × {d.minHeight||'auto'}{free?` · X ${d.x||0} Y ${d.y||0}`:''}</div><div className="visual-width-presets" onPointerDown={e=>e.stopPropagation()}>{['auto','25%','33%','50%','66%','75%','100%'].map(v=><button type="button" key={v} onClick={()=>fitWidth(v)}>{v==='auto'?'Auto':v}</button>)}</div>{free?<button type="button" className="free-move-handle" aria-label="Mover elemento" title="Arraste para mover livremente" onPointerDown={startMove}><Move size={15}/> Mover</button>:null}<button type="button" className="resize-handle resize-right" aria-label="Ajustar largura" onPointerDown={e=>startResize('x',e)}/><button type="button" className="resize-handle resize-bottom" aria-label="Ajustar altura" onPointerDown={e=>startResize('y',e)}/><button type="button" className="resize-handle resize-corner" aria-label="Ajustar largura e altura" onPointerDown={e=>startResize('xy',e)}/></div>
}
