-- Estrutura inicial para migração do protótipo local ao Supabase.
create extension if not exists pgcrypto;
create table if not exists companies (id uuid primary key default gen_random_uuid(), name text not null, created_at timestamptz default now());
create table if not exists catalog_nodes (id uuid primary key default gen_random_uuid(), company_id uuid references companies(id) on delete cascade, parent_id uuid references catalog_nodes(id) on delete cascade, kind text not null check (kind in ('department','category','section','subcategory','distribution')), name text not null, sort_order int default 0, active boolean default true);
create table if not exists products (id uuid primary key default gen_random_uuid(), company_id uuid references companies(id) on delete cascade, code text not null, name text not null, brand text, department_id uuid references catalog_nodes(id), category_id uuid references catalog_nodes(id), section_id uuid references catalog_nodes(id), subcategory_id uuid references catalog_nodes(id), distribution_id uuid references catalog_nodes(id), price numeric, show_price boolean default false, public_fields jsonb default '{}'::jsonb, active boolean default true, created_at timestamptz default now(), unique(company_id,code));
create table if not exists product_images (id uuid primary key default gen_random_uuid(), product_id uuid references products(id) on delete cascade, path text not null, sort_order int default 0, is_primary boolean default false);
create table if not exists promotions (id uuid primary key default gen_random_uuid(), company_id uuid references companies(id) on delete cascade, name text not null, start_at timestamptz, end_at timestamptz, active boolean default true);
create table if not exists promotion_products (promotion_id uuid references promotions(id) on delete cascade, product_id uuid references products(id) on delete cascade, primary key(promotion_id,product_id));
create table if not exists site_versions (id uuid primary key default gen_random_uuid(), company_id uuid references companies(id) on delete cascade, status text not null check(status in ('draft','published','archived')), config jsonb not null default '{}'::jsonb, created_by uuid, created_at timestamptz default now(), published_at timestamptz);
create table if not exists analytics_events (id bigint generated always as identity primary key, company_id uuid references companies(id) on delete cascade, event_type text not null, entity_type text, entity_id text, search_term text, session_hash text, created_at timestamptz default now());
create index if not exists analytics_events_created_idx on analytics_events(created_at);
create index if not exists analytics_events_entity_idx on analytics_events(entity_type,entity_id);
-- Em produção, habilitar RLS em todas as tabelas e criar policies por company_id / usuário autenticado.
