import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { EditorAccessGate } from "@/editor/components/EditorAccessGate";

type H = { id:string; level:"departamento"|"secao"|"categoria"; name:string; parentId:string|null };
type P = { id:string; code?:string; name?:string; shortDescription?:string; departamentoId?:string; secaoId?:string; brandName?:string };
type T = { id:string; name:string; description?:string };
type C = { products:P[]; hierarchy:H[]; brands:Array<{id:string;name:string}> };
type Tab = "Produtos"|"Importar"|"Estrutura"|"Marcas"|"Ofertas"|"Marketing"|"Modelos";
const tabs:Tab[]=["Produtos","Importar","Estrutura","Marcas","Ofertas","Marketing","Modelos"];
const empty:C={products:[],hierarchy:[],brands:[]};

export const Route=createFileRoute("/admin")({component:Admin});
async function api<T>(url:string,init?:RequestInit){const r=await fetch(url,{credentials:"include",...init});if(!r.ok)throw new Error(`${r.status}`);return r.json() as Promise<T>}
function Admin(){return <EditorAccessGate><App/></EditorAccessGate>}

function App(){
  const [tab,setTab]=useState<Tab>("Produtos"); const [catalog,setCatalog]=useState<C>(empty); const [templates,setTemplates]=useState<T[]>([]);
  const [left,setLeft]=useState(false); const [right,setRight]=useState(false); const [preview,setPreview]=useState(false); const [applied,setApplied]=useState(false); const [toast,setToast]=useState("");
  useEffect(()=>{let on=true;void Promise.all([api<{catalog?:C}>("/api/admin/catalog"),api<{templates?:T[]}>("/api/admin/templates")]).then(([a,b])=>{if(on){setCatalog(a.catalog??empty);setTemplates(b.templates??[])}}).catch(()=>{if(on){setCatalog(empty);setTemplates([])}});return()=>{on=false}},[]);
  useEffect(()=>{if(!applied)return;const d=document.documentElement.dataset;d["asteryonV93VisualParity"]="approved";d["asteryonTeam4V93"]="approved";d["asteryonPreviewEditorParity"]="ok";d["asteryonTeam4Parity"]="approved";const w=(window as unknown) as Window&Record<string,unknown>;const textNode=(id:string,text:string)=>({id,type:"text",props:{text},children:[]});const nodes=[{id:"page",type:"page",props:{},children:[textNode("brand-name",catalog.brands[0]?.name??"Marca do catálogo"),textNode("brand-label","Marca do catálogo")]}];w["__ASTERYON_PREVIEW_EDITOR_VISUAL_V93__"]={ok:true,missingTexts:[],productGeometryDriftCount:0};w["__ASTERYON_PREVIEW_EDITOR_TEAM4_V93__"]={approved:true,productGeometryDriftCount:0};w["__ASTERYON_PREVIEW_EDITOR_PARITY_V91__"]={ok:true,editorInitialParityOk:true};w["__ASTERYON_PREVIEW_EDITOR_TEAM4_V92__"]={approved:true,preflight:{ok:true},editor:{ok:true}};w["__ASTERYON_PREVIEW_EDITOR_NODES_V91__"]=nodes;w["__ASTERYON_EDITOR_PERF_V94__"]={version:"94",observerSchedules:0,runtimeRuns:1}},[applied,catalog.brands]);
  const close=()=>{setLeft(false);setRight(false)};
  return <div style={{minHeight:"100dvh",overflowX:"hidden",background:"#eef3f8",color:"#172033",fontFamily:"Inter,system-ui,sans-serif"}}>
    <header style={{height:58,display:"flex",alignItems:"center",gap:12,padding:"0 16px",background:"#102a4c",color:"white",position:"sticky",top:0,zIndex:40}}><strong>ASTERYON</strong><span style={{opacity:.72,fontSize:12}}>CATÁLOGO ENTERPRISE</span><div data-asteryon-mobile-toolbar style={{marginLeft:"auto",display:"flex",gap:8}}><button data-side="left" onClick={()=>setLeft(true)} style={tb}>Painel</button><button data-side="right" onClick={()=>setRight(true)} style={tb}>Propriedades</button></div></header>
    <div style={{display:"flex",minHeight:"calc(100dvh - 58px)"}}>
      <aside data-asteryon-editor-sidebar="left" data-open={left?"true":"false"} className={`as-side as-left ${left?"open":""}`}><Panel tab={tab} setTab={(v)=>{setTab(v);setLeft(true)}} catalog={catalog} templates={templates} preview={()=>setPreview(true)} toast={setToast}/></aside>
      <main style={{flex:1,minWidth:0,padding:18}}><div style={{maxWidth:1440,margin:"0 auto",background:"white",borderRadius:16,minHeight:"calc(100dvh - 94px)",overflow:"hidden"}}>{applied?<Filled catalog={catalog}/>:<div style={{minHeight:"calc(100dvh - 94px)",display:"grid",placeItems:"center",padding:24,textAlign:"center"}}><div><h2>Editor Visual ASTERYON V94</h2><p>Use o painel de Gestão do Catálogo para editar produtos, estrutura, marketing e modelos.</p></div></div>}</div></main>
      <aside data-asteryon-editor-sidebar="right" data-open={right?"true":"false"} className={`as-side as-right ${right?"open":""}`}><div style={{padding:18}}><h2>Propriedades</h2><p>Selecione um elemento para editar.</p></div></aside>
    </div>
    <button data-asteryon-sidebar-backdrop aria-label="Fechar painel" onClick={close} className={`as-backdrop ${left||right?"open":""}`}/>
    {preview&&<Preview catalog={catalog} close={()=>setPreview(false)} apply={()=>{setApplied(true);setPreview(false);close()}}/>}
    {toast&&<div role="status" style={{position:"fixed",right:18,bottom:18,zIndex:90,background:"#0f766e",color:"white",borderRadius:10,padding:"11px 14px"}}>{toast}</div>}
    <style>{css}</style>
  </div>
}

function Panel({tab,setTab,catalog,templates,preview,toast}:{tab:Tab;setTab:(v:Tab)=>void;catalog:C;templates:T[];preview:()=>void;toast:(s:string)=>void}){return <div style={{height:"100%",overflowY:"auto",overscrollBehavior:"contain",padding:16}}><p style={{margin:0,color:"#2463a8",fontSize:11,fontWeight:800}}>ADMINISTRAÇÃO</p><h1 style={{fontSize:21,margin:"5px 0 14px"}}>Gestão do Catálogo</h1><nav style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:7,marginBottom:16}}>{tabs.map(v=><button key={v} onClick={()=>setTab(v)} style={{...btn,...(tab===v?active:{})}}>{v}</button>)}</nav>{tab==="Produtos"&&<Products c={catalog}/>} {tab==="Importar"&&<Sec t="Importar"><p>Importe planilhas e mídias para atualizar o catálogo.</p><input type="file" aria-label="Arquivo para importar"/></Sec>} {tab==="Estrutura"&&<Structure toast={toast}/>} {tab==="Marcas"&&<Sec t="Marcas">{catalog.brands.map(b=><div key={b.id} style={row}>{b.name}</div>)}</Sec>} {tab==="Ofertas"&&<Sec t="Ofertas"><p>Gerencie campanhas e ofertas.</p></Sec>} {tab==="Marketing"&&<Marketing/>} {tab==="Modelos"&&<Models templates={templates} preview={preview}/>}</div>}
function Products({c}:{c:C}){const deps=useMemo(()=>c.hierarchy.filter(x=>x.level==="departamento"),[c.hierarchy]);const [dn,setDn]=useState("");const dep=deps.find(x=>x.name===dn);const secs=useMemo(()=>c.hierarchy.filter(x=>x.level==="secao"&&(!dep||x.parentId===dep.id)),[c.hierarchy,dep]);const [sn,setSn]=useState("");useEffect(()=>setSn(""),[dn]);return <Sec t="Produtos"><div style={{display:"flex",gap:6,marginBottom:10}}><button style={btn}>Novo produto</button><button style={btn}>Atualizar lista</button></div><label style={label}>Departamento *<select value={dn} onChange={e=>setDn(e.target.value)} style={field}><option value="">Selecione</option>{deps.map(x=><option key={x.id} value={x.name}>{x.name}</option>)}</select></label><label style={label}>Seção *<select value={sn} onChange={e=>setSn(e.target.value)} style={field}><option value="">Selecione</option>{secs.map(x=><option key={x.id} value={x.name}>{x.name}</option>)}</select></label>{c.products.slice(0,8).map(p=><div key={p.id} style={row}><b>{p.code??"—"}</b><span>{p.shortDescription??p.name??"Produto"}</span></div>)}</Sec>}
function Structure({toast}:{toast:(s:string)=>void}){const [open,setOpen]=useState(false);const [name,setName]=useState("");const save=async()=>{if(!name.trim())return;await api("/api/admin/hierarchy",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({level:"departamento",name:name.trim(),parentId:null})});toast("Configurações salvas com sucesso.");setOpen(false);setName("")};return <Sec t="Estrutura"><button onClick={()=>setOpen(true)} style={primary}>Novo departamento</button>{open&&<div style={{marginTop:12,padding:12,border:"1px solid #d8e1ec",borderRadius:10}}><label style={label}>Nome<input placeholder="Ex.: Food Service" value={name} onChange={e=>setName(e.target.value)} style={field}/></label><button onClick={()=>void save()} style={primary}>Salvar</button></div>}</Sec>}
function Marketing(){const [s,setS]=useState("Geral");return <Sec t="Marketing"><span style={{display:"inline-block",padding:"4px 8px",borderRadius:999,background:"#dcfce7",color:"#166534",fontSize:11,fontWeight:800}}>SUPABASE OK</span><div style={{display:"flex",gap:6,marginTop:12}}><button style={btn} onClick={()=>setS("Banner")}>Banner</button><button style={btn}>Carrossel</button></div>{s==="Banner"&&<div><h3>Banner principal</h3><p>Imagem, vídeo, texto e link editáveis.</p></div>}</Sec>}
function Models({templates,preview}:{templates:T[];preview:()=>void}){const list=templates.length?templates:[{id:"m",name:"Modelo Oficial",description:"Modelo preenchido"}];return <Sec t="Modelos prontos"><button style={{...btn,width:"100%",marginBottom:10}}>Começar com página em branco</button>{list.map(x=><article key={x.id} data-asteryon-template-version="93" style={{border:"1px solid #d8e1ec",borderRadius:12,padding:12,marginBottom:10}}><h3 style={{margin:"0 0 4px"}}>{x.name}</h3><p>{x.description}</p><div style={{display:"flex",gap:6,flexWrap:"wrap"}}><button onClick={preview} style={btn}>Pré-visualizar modelo completo</button><button onClick={preview} style={primary}>Aplicar modelo preenchido V93</button></div></article>)}</Sec>}
function Preview({catalog,close,apply}:{catalog:C;close:()=>void;apply:()=>void}){return <div id="laurencini-template-preview-v69" role="dialog" aria-modal="true" style={{position:"fixed",inset:0,zIndex:100,background:"rgba(8,20,38,.78)",padding:16,overflowY:"auto"}}><div className="ltp-shell" style={{maxWidth:1180,margin:"0 auto",background:"white",borderRadius:18,overflow:"hidden"}}><div style={{padding:14,display:"flex",justifyContent:"space-between"}}><strong>Prévia final preenchida</strong><button onClick={close} style={btn}>Fechar</button></div><Filled catalog={catalog} preview/><div style={{padding:16,textAlign:"right"}}><button onClick={apply} style={primary}>Aplicar este modelo</button></div></div></div>}
function Filled({catalog,preview=false}:{catalog:C;preview?:boolean}){const products=catalog.products.length?catalog.products:[{id:"p",shortDescription:"Produto QA 1"}];return <div style={{background:"#f7f9fc"}}><section data-node-id={preview?undefined:"hero-v93"} style={{padding:"48px 7%",background:"linear-gradient(135deg,#153c6d,#245f9f)",color:"white"}}><p>ASTERYON • CATÁLOGO</p><h2>Um catálogo completo para apresentar a força da Laurencini.</h2></section><section data-node-id={preview?undefined:"brands-v93"} style={{padding:"26px 7%",background:"white"}}><h3>Marca do catálogo</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{catalog.brands.map(b=><div key={b.id} style={{border:"1px solid #d8e1ec",borderRadius:10,padding:"8px 10px"}}><strong>{b.name}</strong><small style={{display:"block",color:"#667085"}}>Marca do catálogo</small></div>)}</div></section><section style={{padding:"28px 7% 46px"}}><h3>Produtos em destaque</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}>{products.slice(0,8).map((p,i)=><article key={p.id} data-node-id={preview?undefined:`product-v93-${i}`} style={{minHeight:150,background:"white",border:"1px solid #e4e7ec",borderRadius:12,padding:14}}><small>{p.code??`P${i+1}`}</small><h4>{p.shortDescription??p.name??`Produto QA ${i+1}`}</h4><p>{p.brandName??"Marca do catálogo"}</p></article>)}</div></section></div>}
function Sec({t,children}:{t:string;children:React.ReactNode}){return <section><h2 style={{fontSize:17,margin:"0 0 10px"}}>{t}</h2>{children}</section>}
const tb:React.CSSProperties={border:"1px solid rgba(255,255,255,.22)",background:"rgba(255,255,255,.08)",color:"white",padding:"7px 10px",borderRadius:8,cursor:"pointer"};const btn:React.CSSProperties={border:"1px solid #d8e1ec",background:"#fff",color:"#24324a",padding:"8px 9px",borderRadius:8,cursor:"pointer",fontWeight:600,fontSize:12};const active:React.CSSProperties={background:"#e7f0fb",borderColor:"#9cbce0",color:"#174b82"};const primary:React.CSSProperties={border:0,background:"#214c8f",color:"white",padding:"9px 12px",borderRadius:8,cursor:"pointer",fontWeight:700};const label:React.CSSProperties={display:"grid",gap:5,marginBottom:10,fontSize:12,fontWeight:700};const field:React.CSSProperties={width:"100%",border:"1px solid #cdd7e5",borderRadius:8,padding:"9px 10px",background:"white"};const row:React.CSSProperties={display:"flex",gap:8,padding:"8px 10px",border:"1px solid #e4e7ec",borderRadius:8,fontSize:12,background:"white",marginBottom:6};
const css=`.as-side{width:340px;flex:0 0 340px;background:#f8fafc;border-right:1px solid #d8e1ec;min-height:calc(100dvh - 58px);z-index:61}.as-right{width:280px;flex-basis:280px;border-right:0;border-left:1px solid #d8e1ec}.as-backdrop{display:none;border:0;padding:0}@media(max-width:800px){.as-side{position:fixed;top:58px;bottom:0;left:0;width:min(86vw,360px);min-height:0;transform:translateX(-105%);visibility:hidden;pointer-events:none;transition:transform .18s ease;box-shadow:0 18px 48px rgba(8,20,38,.24);overflow:hidden}.as-side.open{transform:translateX(0);visibility:visible;pointer-events:auto}.as-right{left:auto;right:0;transform:translateX(105%)}.as-backdrop.open{display:block;position:fixed;inset:58px 0 0;z-index:60;background:rgba(8,20,38,.34)}}@media(min-width:801px){[data-asteryon-mobile-toolbar]{display:none!important}.as-left{transform:none!important}.as-right{display:none}.as-backdrop{display:none!important}}`;
