import { useEffect, useMemo, useState } from 'react';
import { Check, Cloud, LayoutTemplate, RefreshCw, RotateCcw, Save, Trash2 } from 'lucide-react';
import { useEditor } from './store';
import { VISUAL_TEMPLATES, type VisualTemplate } from './templates';
import { cloudApi, isCloudRuntime, type CloudTemplate } from '../cloud/api';

export function TemplatesPanel() {
  const { state, dispatch } = useEditor();
  const [applied, setApplied] = useState<string | null>(null);
  const [cloudTemplates, setCloudTemplates] = useState<CloudTemplate[]>([]);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');
  const cloud = isCloudRuntime();
  const builtIns = useMemo(() => VISUAL_TEMPLATES.map((template) => ({ systemKey: template.id, name: template.name, description: template.description, category: 'pre-pronto', tags: template.tags, accent: template.accent, nodes: template.build() })), []);

  const loadCloudTemplates = async () => { if (!cloud) return; setLoading(true); setMessage(''); try { try { await cloudApi.seedTemplates(builtIns); } catch {} const result = await cloudApi.listTemplates(); setCloudTemplates(result.templates); } catch (err) { setMessage(err instanceof Error ? err.message : 'Falha ao carregar modelos'); } finally { setLoading(false); } };
  useEffect(() => { void loadCloudTemplates(); }, [cloud]);
  const applyNodes = (id:string,name:string,nodes:typeof state.nodes) => { const hasContent=state.nodes.some(node=>node.type==='page'&&(node.children?.length??0)>0); if(hasContent&&!window.confirm(`Aplicar o modelo “${name}” vai substituir o conteúdo atual da página. Deseja continuar?`))return; dispatch({type:'CREATE_SNAPSHOT',label:`Antes do modelo ${name}`});dispatch({type:'REPLACE_NODES',nodes:JSON.parse(JSON.stringify(nodes))});dispatch({type:'SET_ZOOM',zoom:.55});dispatch({type:'SET_PAN',pan:{x:120,y:60}});setApplied(id); };
  const updateFromCurrentPage=async(template:CloudTemplate)=>{if(!window.confirm(`Substituir o modelo “${template.name}” pelo layout atual?`))return;try{await cloudApi.updateTemplate(template.id,{nodes:state.nodes});await loadCloudTemplates();setMessage('Modelo atualizado no D1.');}catch(err){setMessage(err instanceof Error?err.message:'Falha ao atualizar modelo')}};
  const removeCloudTemplate=async(template:CloudTemplate)=>{if(!window.confirm(`Excluir o modelo “${template.name}” da biblioteca?`))return;try{await cloudApi.deleteTemplate(template.id);await loadCloudTemplates();}catch(err){setMessage(err instanceof Error?err.message:'Falha ao excluir modelo')}};
  const blankPage=()=>{const page=VISUAL_TEMPLATES[0].build()[0];page.name='Página em branco';page.height=5200;page.styles={backgroundColor:'#fff'};page.children=[];dispatch({type:'CREATE_SNAPSHOT',label:'Antes de limpar página'});dispatch({type:'REPLACE_NODES',nodes:[page]});setApplied(null)};
  const localMode=!cloud||cloudTemplates.length===0;
  return <div className="flex h-full flex-col bg-zinc-900"><div className="border-b border-zinc-800 px-3 py-3"><div className="flex items-center justify-between gap-2"><div><h3 className="text-xs font-semibold uppercase tracking-wider text-zinc-300">Modelos prontos</h3><p className="mt-1 text-[10px] leading-relaxed text-zinc-500">No D1, o SDM pode substituir ou remover qualquer modelo. Depois de aplicar, cada objeto continua livre.</p></div><div className="flex items-center gap-2"><LayoutTemplate size={18} className="text-blue-400"/>{cloud&&<button onClick={()=>void loadCloudTemplates()} className="text-zinc-500 hover:text-white"><RefreshCw size={14} className={loading?'animate-spin':''}/></button>}</div></div>{message&&<div className="mt-2 rounded border border-zinc-800 bg-zinc-950 px-2 py-1 text-[9px] text-zinc-400">{message}</div>}</div><div className="flex-1 space-y-3 overflow-y-auto p-3">{localMode?VISUAL_TEMPLATES.map(t=><LocalCard key={t.id} template={t} applied={applied===t.id} onApply={()=>applyNodes(t.id,t.name,t.build())}/>):cloudTemplates.map(t=><CloudCard key={t.id} template={t} applied={applied===t.id} onApply={()=>applyNodes(t.id,t.name,t.nodes)} onUpdate={()=>void updateFromCurrentPage(t)} onDelete={()=>void removeCloudTemplate(t)}/>)}</div><div className="border-t border-zinc-800 p-3"><button onClick={blankPage} className="flex w-full items-center justify-center gap-2 rounded-lg border border-zinc-700 bg-zinc-900 py-2 text-[10px] font-semibold text-zinc-400 hover:text-white"><RotateCcw size={13}/> Começar com página em branco</button></div></div>;
}
function LocalCard({template,applied,onApply}:{template:VisualTemplate;applied:boolean;onApply:()=>void}){return <article className="overflow-hidden rounded-xl border border-zinc-800 bg-zinc-950/60"><TemplatePreview accent={template.accent}/><div className="p-3"><div className="flex items-start justify-between"><h4 className="text-xs font-bold text-zinc-100">{template.name}</h4>{applied&&<Check size={15} className="text-emerald-400"/>}</div><p className="mt-2 text-[10px] text-zinc-400">{template.description}</p><button onClick={onApply} className="mt-3 w-full rounded-lg bg-blue-600 py-2 text-[10px] font-bold text-white">Aplicar modelo</button></div></article>}
function CloudCard({template,applied,onApply,onUpdate,onDelete}:{template:CloudTemplate;applied:boolean;onApply:()=>void;onUpdate:()=>void;onDelete:()=>void}){return <article className="overflow-hidden rounded-xl border border-zinc-800 bg-zinc-950/60"><TemplatePreview accent={template.accent||'#2563eb'}/><div className="p-3"><div className="flex items-start justify-between"><div><h4 className="text-xs font-bold text-zinc-100">{template.name}</h4><p className="mt-1 flex items-center gap-1 text-[9px] text-blue-500"><Cloud size={9}/> D1 · v{template.version}</p></div>{applied&&<Check size={15} className="text-emerald-400"/>}</div><p className="mt-2 text-[10px] text-zinc-400">{template.description}</p><button onClick={onApply} className="mt-3 w-full rounded-lg bg-blue-600 py-2 text-[10px] font-bold text-white">Aplicar modelo</button><div className="mt-2 grid grid-cols-2 gap-2"><button onClick={onUpdate} className="flex items-center justify-center gap-1 rounded border border-zinc-700 py-1.5 text-[9px] text-zinc-400"><Save size={10}/> Atualizar</button><button onClick={onDelete} className="flex items-center justify-center gap-1 rounded border border-zinc-700 py-1.5 text-[9px] text-zinc-400"><Trash2 size={10}/> Excluir</button></div></div></article>}
function TemplatePreview({accent}:{accent:string}){return <div className="relative h-28 overflow-hidden bg-zinc-100" style={{borderTop:`3px solid ${accent}`}}><div className="absolute left-3 right-3 top-3 h-3 rounded bg-white"/><div className="absolute left-3 top-8 h-8 w-[62%] rounded" style={{background:`linear-gradient(120deg, ${accent}, #111827)`}}/><div className="absolute right-3 top-8 h-8 w-[28%] rounded bg-white"/><div className="absolute left-3 right-3 top-[4.5rem] grid grid-cols-4 gap-1.5">{Array.from({length:4}).map((_,i)=><div key={i} className="h-8 rounded bg-white"><div className="m-1 h-3 rounded bg-zinc-200"/><div className="mx-1 h-1.5 w-2/3 rounded bg-zinc-300"/></div>)}</div></div>}
