import type{EditorNode}from'../editor/types';

export type ActionContext='automatic'|'product'|'brand'|'department'|'section'|'category'|'promotion'|'marketing'|'contact'|'custom';
export type NodeActionType='none'|'url'|'scroll'|'top'|'product-info'|'product-page'|'product-details'|'product-technical'|'product-composition'|'product-nutrition'|'product-gallery'|'product-video'|'product-catalog-pdf'|'product-technical-pdf'|'favorite'|'compare'|'product-similar'|'product-category'|'product-brand'|'quote-request'|'quote-add'|'order-add'|'buy-now'|'seller'|'support'|'brand-page'|'brand-products'|'brand-promotions'|'brand-catalog'|'brand-launches'|'brand-featured'|'department-page'|'department-categories'|'department-products'|'department-promotions'|'department-featured'|'section-page'|'section-products'|'section-categories'|'section-promotions'|'category-page'|'category-products'|'category-related'|'category-promotions'|'promotion-page'|'promotion-product'|'promotion-order-add'|'promotion-quote'|'banner-open'|'campaign-open'|'flyer-open'|'promo-video'|'campaign-participate'|'showcase-open'|'whatsapp'|'telegram'|'phone'|'email'|'chat'|'modal'|'popup'|'custom-page'|'custom-action'|'custom-form';
export interface ResolvedNodeAction{type:NodeActionType;value:string;message:string;target:string;context:ActionContext;inferred:boolean}

const PRODUCT_ACTIONS=new Set<NodeActionType>(['product-info','product-page','product-details','product-technical','product-composition','product-nutrition','product-gallery','product-video','product-catalog-pdf','product-technical-pdf','favorite','compare','product-similar','product-category','product-brand','quote-request','quote-add','order-add','buy-now','seller','support']);
const BRAND_ACTIONS=new Set<NodeActionType>(['brand-page','brand-products','brand-promotions','brand-catalog','brand-launches','brand-featured']);
const DEPARTMENT_ACTIONS=new Set<NodeActionType>(['department-page','department-categories','department-products','department-promotions','department-featured']);
const SECTION_ACTIONS=new Set<NodeActionType>(['section-page','section-products','section-categories','section-promotions']);
const CATEGORY_ACTIONS=new Set<NodeActionType>(['category-page','category-products','category-related','category-promotions']);
const PROMOTION_ACTIONS=new Set<NodeActionType>(['promotion-page','promotion-product','promotion-order-add','promotion-quote']);
const MARKETING_ACTIONS=new Set<NodeActionType>(['banner-open','campaign-open','flyer-open','promo-video','campaign-participate','showcase-open']);
const CONTACT_ACTIONS=new Set<NodeActionType>(['whatsapp','telegram','phone','email','chat','support','seller']);
function normalize(value:unknown){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function has(text:string,...terms:string[]){return terms.some(term=>text.includes(normalize(term)))}
function contextFor(type:NodeActionType):ActionContext{if(PRODUCT_ACTIONS.has(type))return'product';if(BRAND_ACTIONS.has(type))return'brand';if(DEPARTMENT_ACTIONS.has(type))return'department';if(SECTION_ACTIONS.has(type))return'section';if(CATEGORY_ACTIONS.has(type))return'category';if(PROMOTION_ACTIONS.has(type))return'promotion';if(MARKETING_ACTIONS.has(type))return'marketing';if(CONTACT_ACTIONS.has(type))return'contact';if(['modal','popup','custom-page','custom-action','custom-form'].includes(type))return'custom';return'automatic'}
function base(node:EditorNode,type:NodeActionType,value='',inferred=false):ResolvedNodeAction{return{type,value,message:String(node.props?.actionMessage||'').trim(),target:String(node.props?.actionTarget||'same'),context:contextFor(type),inferred}}
export function inferActionContext(node:EditorNode):ActionContext{const explicit=String(node.props?.actionContext||'') as ActionContext;if(['product','brand','department','section','category','promotion','marketing','contact','custom'].includes(explicit))return explicit;if(node.type==='productbutton'||String(node.type).startsWith('product')||node.props?.productId)return'product';if(node.props?.brandId)return'brand';if(node.props?.departmentId)return'department';if(node.props?.sectionId)return'section';if(node.props?.categoryId)return'category';if(node.props?.promotionId)return'promotion';return'automatic'}
export function inferAnchorId(node:EditorNode){const explicit=String(node.props?.anchorId||'').trim().replace(/^#/,'');if(explicit)return explicit;const text=normalize(`${node.name||''} ${node.props?.text||''}`);if(has(text,'contato','fale conosco','representante','atendimento'))return'contato';if(has(text,'depoimento','testemunho'))return'depoimentos';if(has(text,'como comprar','como funciona'))return'como-comprar';if(has(text,'quem somos','institucional','sobre a empresa'))return'quem-somos';if(has(text,'promocao','promoção','oferta','campanha'))return'promocoes';if(has(text,'catalogo','catálogo','produtos','vitrine','departamento','categorias'))return'catalogo';return''}

export function resolveNodeAction(node:EditorNode):ResolvedNodeAction{
  const explicit=String(node.props?.actionType||'none') as NodeActionType;const value=String(node.props?.actionEntityId||node.props?.actionValue||'').trim();const productId=String(node.props?.productId||'').trim();if(explicit!=='none')return base(node,explicit,value||(PRODUCT_ACTIONS.has(explicit)?productId:''),false);
  if(node.type!=='button'&&node.type!=='productbutton')return base(node,'none','',false);if(productId)return base(node,'product-info',productId,true);const label=normalize(`${node.props?.text||''} ${node.name||''}`);if(has(label,'area do lojista','abrir editor','entrar','login','administracao','administração'))return base(node,'url','/admin',true);if(has(label,'whatsapp'))return base(node,'whatsapp',String(node.props?.whatsapp||node.props?.phone||''),true);if(has(label,'telefone','ligar'))return base(node,'phone',String(node.props?.phone||''),true);if(has(label,'email','e mail'))return base(node,'email',String(node.props?.email||''),true);if(has(label,'falar com representante','fale conosco','solicitar atendimento','quero comprar','comprar agora'))return base(node,'scroll','#contato',true);if(has(label,'promocoes','promoções','ofertas'))return base(node,'scroll','#promocoes',true);if(has(label,'catalogo','catálogo','produtos','mix completo'))return base(node,'scroll','#catalogo',true);if(has(label,'voltar ao topo','inicio','início'))return base(node,'top','',true);return base(node,'scroll','#catalogo',true)
}
function scrollToAnchor(value:string){const id=String(value||'').replace(/^#/,'').trim();if(!id)return false;const target=document.getElementById(id)||Array.from(document.querySelectorAll<HTMLElement>('[data-catalog-anchor]')).find(item=>item.dataset.catalogAnchor===id);if(target){target.scrollIntoView({behavior:'smooth',block:'start'});return true}window.location.hash=id;return true}
function notice(message:string){window.dispatchEvent(new CustomEvent('asteryon:notice',{detail:{message}}))}
function stored(key:string){try{return JSON.parse(localStorage.getItem(key)||'[]') as string[]}catch{return[]}}
function saveStored(key:string,id:string,max=100){const list=stored(key);if(!list.includes(id))list.push(id);localStorage.setItem(key,JSON.stringify(list.slice(-max)));return list}
function productRoute(id:string,view='info'){return `/produto/${encodeURIComponent(id)}${view&&view!=='info'?`?view=${encodeURIComponent(view)}`:''}`}
function brandRoute(id:string,view='brand'){return `/marca/${encodeURIComponent(id)}${view!=='brand'?`?view=${encodeURIComponent(view)}`:''}`}
function entityRoute(kind:string,id:string,view:string){const p=new URLSearchParams();p.set(kind,id);if(view)p.set('view',view);return `/?${p.toString()}#catalogo`}
function openValue(value:string,target='same'){if(!value)return false;if(value.startsWith('#'))return scrollToAnchor(value);if(target==='new')window.open(value,'_blank','noopener,noreferrer');else window.location.assign(value);return true}
function go(url:string,target='same'){if(window.location.pathname.startsWith('/admin/')){window.open(url,'_blank','noopener,noreferrer');return true}return openValue(url,target)}
export function executeNodeAction(node:EditorNode){if(typeof window==='undefined')return false;const action=resolveNodeAction(node),{type,value,message,target}=action;const id=value||String(node.props?.productId||node.props?.brandId||node.props?.categoryId||'').trim();if(type==='none')return false;if(type==='scroll')return scrollToAnchor(value);if(type==='url'||type==='custom-page')return openValue(value,target);if(type==='top'){window.scrollTo({top:0,behavior:'smooth'});return true}
  if(PRODUCT_ACTIONS.has(type)){
    if(!id){notice('Selecione um produto para esta ação.');return false}const viewMap:Record<string,string>={'product-info':'info','product-page':'info','product-details':'details','product-technical':'technical','product-composition':'composition','product-nutrition':'nutrition','product-gallery':'gallery','product-video':'video','product-catalog-pdf':'catalog-pdf','product-technical-pdf':'technical-pdf','product-similar':'similar','product-category':'category','product-brand':'brand'};
    if(type==='favorite'){saveStored('asteryon.favorites',id);notice('Produto adicionado aos favoritos.');return true}if(type==='compare'){const list=saveStored('asteryon.compare',id,4);notice(`Produto adicionado à comparação (${list.length}/4).`);return true}if(type==='quote-add'||type==='quote-request'){saveStored('asteryon.quote',id);notice('Produto adicionado à cotação.');if(type==='quote-request')setTimeout(()=>scrollToAnchor('#contato'),250);return true}if(type==='order-add'||type==='buy-now'){saveStored('asteryon.order',id);notice('Produto adicionado ao pedido.');if(type==='buy-now')setTimeout(()=>scrollToAnchor('#contato'),250);return true}if(type==='seller'||type==='support'){saveStored('asteryon.serviceProduct',id,1);return scrollToAnchor('#contato')}return go(productRoute(id,viewMap[type]||'info'),target)
  }
  if(BRAND_ACTIONS.has(type)){if(!id){notice('Selecione uma marca.');return false}const view:{[key:string]:string}={'brand-page':'brand','brand-products':'products','brand-promotions':'promotions','brand-catalog':'catalog','brand-launches':'launches','brand-featured':'featured'};return go(brandRoute(id,view[type]||'brand'),target)}
  if(DEPARTMENT_ACTIONS.has(type)){if(!id)return false;return go(entityRoute('departamento',id,type.replace('department-','')),target)}if(SECTION_ACTIONS.has(type)){if(!id)return false;return go(entityRoute('secao',id,type.replace('section-','')),target)}if(CATEGORY_ACTIONS.has(type)){if(!id)return false;return go(entityRoute('categoria',id,type.replace('category-','')),target)}if(PROMOTION_ACTIONS.has(type)){if(!id)return false;return go(`/?promocao=${encodeURIComponent(id)}&view=${encodeURIComponent(type.replace('promotion-',''))}#promocoes`,target)}
  if(MARKETING_ACTIONS.has(type)){if(value)return openValue(value,target);const anchors:Record<string,string>={'banner-open':'#topo','campaign-open':'#promocoes','flyer-open':'#promocoes','promo-video':'#topo','campaign-participate':'#contato','showcase-open':'#promocoes'};return scrollToAnchor(anchors[type]||'#topo')}
  if(type==='whatsapp'){const digits=value.replace(/\D/g,'');if(!digits)return scrollToAnchor('#contato');window.open(`https://wa.me/${digits}${message?`?text=${encodeURIComponent(message)}`:''}`,'_blank','noopener,noreferrer');return true}if(type==='telegram'){const user=value.replace(/^@/,'').trim();if(!user)return scrollToAnchor('#contato');window.open(`https://t.me/${encodeURIComponent(user)}`,'_blank','noopener,noreferrer');return true}if(type==='phone'){const phone=value.replace(/[^\d+]/g,'');if(!phone)return scrollToAnchor('#contato');window.location.href=`tel:${phone}`;return true}if(type==='email'){if(!value.includes('@'))return scrollToAnchor('#contato');window.location.href=`mailto:${value}${message?`?subject=${encodeURIComponent(message)}`:''}`;return true}if(type==='chat'){window.dispatchEvent(new CustomEvent('asteryon:custom-action',{detail:{type:'chat',value,message}}));return true}
  if(['modal','popup','custom-action','custom-form'].includes(type)){window.dispatchEvent(new CustomEvent('asteryon:custom-action',{detail:{type,value,message,title:String(node.props?.actionTitle||node.props?.text||'')}}));return true}return false
}
