import{useState,type ChangeEvent}from'react';
import*as XLSX from'xlsx';
import{AlertTriangle,CheckCircle2,FileSpreadsheet,Images,Loader2}from'lucide-react';
import{useCatalog}from'../catalog/store';
import{cloudApi,isCloudRuntime}from'./api';
import{productionApi}from'./productionApi';

const K=(v:unknown)=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'');
function cell(r:Record<string,unknown>,names:string[]){const m=new Map(Object.entries(r).map(([k,v])=>[K(k),v]));for(const n of names){const v=m.get(K(n));if(v!==undefined&&String(v).trim())return String(v).trim()}return''}
function num(v:string){let s=v.replace(/\s|R\$/gi,'');if(!s)return null;const c=s.lastIndexOf(','),d=s.lastIndexOf('.');if(c>=0&&d>=0)s=c>d?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else if(c>=0)s=s.replace(',','.');const n=Number(s.replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:null}
function productRow(r:Record<string,unknown>){const code=cell(r,['codigo','código','codproduto','sku','code']),description=cell(r,['descricao','descrição','produto','nome']),department=cell(r,['departamento','department']),section=cell(r,['secao','seção','section']),category=cell(r,['categoria','category']);if(!code||!description||!department||!section||!category)return null;const ean=cell(r,['ean','gtin','codigo barras']),ncm=cell(r,['ncm']),packaging=cell(r,['embalagem']),unit=cell(r,['unidade','unit','un'])||'UN',price=num(cell(r,['preco','preço','valor'])),promoPrice=num(cell(r,['preco promocional','preço promocional','promo'])),stock=num(cell(r,['estoque','stock','saldo']));const known=['codigo','código','codproduto','sku','code','descricao','descrição','produto','nome','ean','gtin','codigo barras','ncm','embalagem','unidade','unit','un','preco','preço','valor','preco promocional','preço promocional','promo','estoque','stock','saldo','marca','brand','departamento','department','secao','seção','section','categoria','category'];const attributes:Record<string,string>={};for(const[k,v]of Object.entries(r)){if(!known.some(n=>K(n)===K(k))&&String(v??'').trim())attributes[k]=String(v).trim()}return{code,name:description,shortDescription:description,longDescription:cell(r,['descricao longa','descrição longa','detalhes'])||description,ean,ncm,packaging,unit,price,promoPrice,stock,brandName:cell(r,['marca','brand']),departamentoName:department,secaoName:section,categoriaName:category,technical:{NCM:ncm,EAN:ean,Embalagem:packaging,Unidade:unit},attributes,tags:[],status:/inativ/i.test(cell(r,['status','situacao']))?'inativo':'ativo',priceMode:price!==null?'valor':'consulte'}}
function findProduct(filename:string,products:any[]){const base=K(filename.replace(/\.[^.]+$/,'')),plain=K(filename.replace(/\.[^.]+$/,'').replace(/(?:[_\-\s](?:foto|img|imagem)?\d+)$/i,''));return products.find(p=>[K(p.code),K(p.ean)].includes(base)||[K(p.code),K(p.ean)].includes(plain))}
function compress(file:File):Promise<File>{return new Promise((resolve,reject)=>{const rd=new FileReader();rd.onerror=()=>reject(new Error(`Falha ao ler ${file.name}`));rd.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error(`Imagem inválida: ${file.name}`));img.onload=()=>{const limit=1800,scale=Math.min(1,limit/Math.max(img.naturalWidth||1,img.naturalHeight||1)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d');if(!ctx)return reject(new Error('Falha ao processar imagem.'));ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(img,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>blob?resolve(new File([blob],`${file.name.replace(/\.[^.]+$/,'')}.webp`,{type:'image/webp'})):reject(new Error('Falha ao otimizar imagem.')),'image/webp',0.92)};img.src=String(rd.result||'')};rd.readAsDataURL(file)})}
export function CatalogImportPanelV2(){
  const catalog=useCatalog(),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
  const sheet=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;if(!isCloudRuntime())return setMsg('Importação disponível somente no editor online.');setBusy(true);try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]];if(!ws)throw new Error('Planilha sem aba válida.');const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(ws,{defval:'',raw:false});const products=rows.map(productRow).filter(Boolean);if(!products.length)throw new Error('Nenhum produto válido. São obrigatórios Código, Descrição, Departamento, Seção e Categoria.');let inserted=0,updated=0,ignored=0;const errors:string[]=[];for(let i=0;i<products.length;i+=300){const r=await cloudApi.bulkProducts(products.slice(i,i+300),file.name,'spreadsheet');inserted+=r.inserted;updated+=r.updated;ignored+=r.ignored;errors.push(...(r.errors||[]).slice(0,5))}await catalog.reloadCatalog();setMsg(`Planilha processada: ${inserted} novo(s), ${updated} atualizado(s), ${ignored} ignorado(s).${errors[0]?` ${errors[0]}`:''}`)}catch(err){setMsg(err instanceof Error?err.message:'Falha na importação.')}finally{setBusy(false)}};
  const images=async(event:ChangeEvent<HTMLInputElement>)=>{const files=Array.from(event.target.files||[]);event.target.value='';if(!files.length)return;setBusy(true);try{let updated=0,missed=0;for(const file of files){const product:any=findProduct(file.name,catalog.products);if(!product){missed++;continue}const optimized=await compress(file);const media=await productionApi.uploadMedia(optimized,'product-image',String(product.code));const gallery=Array.from(new Set([media.url,...(Array.isArray(product.gallery)?product.gallery:[])])).slice(0,8);const r=await cloudApi.bulkProducts([{...product,name:product.shortDescription||product.code,image:media.url,gallery,status:product.status==='inativo'?'inativo':'ativo',departamentoName:product.departamentoName,secaoName:product.secaoName,categoriaName:product.categoriaName}],`imagem-${product.code}.json`,'images');updated+=r.inserted+r.updated}await catalog.reloadCatalog();setMsg(`${updated} produto(s) com imagem permanente vinculada pelo código.${missed?` ${missed} imagem(ns) sem código/EAN correspondente.`:''}`)}catch(err){setMsg(err instanceof Error?err.message:'Falha nas imagens.')}finally{setBusy(false)}};
  const tone=/falha|inválid|nenhum|obrigat/i.test(msg);return <div className="rounded-lg border border-zinc-800 bg-zinc-950/60 p-3"><div className="grid grid-cols-2 gap-2"><label className={`flex cursor-pointer items-center justify-center gap-2 rounded bg-zinc-800 py-2 text-[10px] font-bold ${busy?'pointer-events-none opacity-50':''}`}>{busy?<Loader2 size={12} className="animate-spin"/>:<FileSpreadsheet size={12}/>}Planilha<input hidden type="file" accept=".xlsx,.xls,.csv" onChange={sheet}/></label><label className={`flex cursor-pointer items-center justify-center gap-2 rounded bg-zinc-800 py-2 text-[10px] font-bold ${busy?'pointer-events-none opacity-50':''}`}><Images size={12}/>Imagens<input hidden type="file" accept="image/*" multiple onChange={images}/></label></div><p className="mt-2 text-[9px] leading-relaxed text-zinc-500">Obrigatórios: Código, Descrição, Departamento, Seção e Categoria. Departamento aceita somente <b>Atacado</b> ou <b>Distribuição</b>. A marca é criada/vinculada automaticamente. A imagem é otimizada sem distorção e associada pelo Código ou EAN.</p>{msg&&<div className={`mt-2 flex gap-1.5 rounded border p-2 text-[9px] ${tone?'border-red-500/20 text-red-300':'border-emerald-500/20 text-emerald-300'}`}>{tone?<AlertTriangle size={11}/>:<CheckCircle2 size={11}/>}<span>{msg}</span></div>}</div>}
