import{useMemo,useState}from'react';
import{FolderTree,Pencil,Plus,Save,Trash2,X}from'lucide-react';
import{useCatalog}from'../catalog/store';
import{productionApi}from'./productionApi';

const C='w-full rounded border border-zinc-700 bg-zinc-950 px-2 py-2 text-[10px] text-zinc-100 outline-none focus:border-blue-500';
type Mode='secao'|'categoria';
export function HierarchyPanel(){
  const catalog=useCatalog();const nodes=(catalog.hierarchy as any[]).filter(n=>n.status!=='inactive');
  const[mode,setMode]=useState<Mode>('secao'),[parentId,setParentId]=useState(''),[name,setName]=useState(''),[editing,setEditing]=useState<any|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const departments=nodes.filter(n=>n.level==='departamento'&&['Atacado','Distribuição'].includes(n.name));const sections=nodes.filter(n=>n.level==='secao');const categories=nodes.filter(n=>n.level==='categoria');
  const tree=useMemo(()=>departments.map(dep=>({...dep,sections:sections.filter(sec=>sec.parentId===dep.id).map(sec=>({...sec,categories:categories.filter(cat=>cat.parentId===sec.id)}))})),[catalog.hierarchy]);
  const reset=()=>{setEditing(null);setName('');setParentId('');setMessage('')};
  const save=async()=>{if(!name.trim())return setMessage('Informe o nome.');if(!editing&&!parentId)return setMessage(mode==='secao'?'Selecione Atacado ou Distribuição.':'Selecione a seção superior.');setBusy(true);try{if(editing)await productionApi.updateHierarchy(editing.id,{name:name.trim(),status:'active',sortOrder:editing.sortOrder||100});else await productionApi.createHierarchy({level:mode,name:name.trim(),parentId,sortOrder:100});await catalog.reloadCatalog();reset();setMessage('Configurações salvas com sucesso.')}catch(error){setMessage(error instanceof Error?error.message:'Falha ao salvar estrutura.')}finally{setBusy(false)}};
  const edit=(node:any)=>{setEditing(node);setMode(node.level as Mode);setName(node.name);setParentId(node.parentId||'');setMessage('')};
  const remove=async(node:any)=>{if(!window.confirm(`Excluir ${node.name}?`))return;setBusy(true);try{await productionApi.deleteHierarchy(node.id);await catalog.reloadCatalog();if(editing?.id===node.id)reset();setMessage('Configurações salvas com sucesso.')}catch(error){setMessage(error instanceof Error?error.message:'Falha ao excluir.')}finally{setBusy(false)}};
  const parents=mode==='secao'?departments:sections;
  return <div className="rounded-xl border border-zinc-800 bg-zinc-900"><Header message={message}/><div className="p-3"><div className="rounded-lg border border-zinc-800 bg-zinc-950/55 p-3"><div className="grid grid-cols-2 gap-2"><button disabled={Boolean(editing)} onClick={()=>{setMode('secao');setParentId('')}} className={`rounded py-2 text-[9px] font-bold ${mode==='secao'?'bg-emerald-600 text-white':'bg-zinc-800 text-zinc-500'}`}>Nova seção</button><button disabled={Boolean(editing)} onClick={()=>{setMode('categoria');setParentId('')}} className={`rounded py-2 text-[9px] font-bold ${mode==='categoria'?'bg-emerald-600 text-white':'bg-zinc-800 text-zinc-500'}`}>Nova categoria</button></div>{!editing&&<><label className="mb-1 mt-3 block text-[9px] text-zinc-500">{mode==='secao'?'Departamento':'Seção'} superior</label><select className={C} value={parentId} onChange={e=>setParentId(e.target.value)}><option value="">Selecione</option>{parents.map((node:any)=><option key={node.id} value={node.id}>{mode==='categoria'?`${departments.find(d=>d.id===sections.find(s=>s.id===node.id)?.parentId)?.name||''} → `:''}{node.name}</option>)}</select></>}<label className="mb-1 mt-3 block text-[9px] text-zinc-500">Nome</label><input className={C} value={name} onChange={e=>setName(e.target.value)} placeholder={mode==='secao'?'Ex.: Bebidas':'Ex.: Refrigerante'}/><div className="mt-3 grid grid-cols-2 gap-2"><button disabled={busy} onClick={()=>void save()} className="flex items-center justify-center gap-1 rounded bg-emerald-600 py-2 text-[10px] font-bold text-white disabled:opacity-50">{editing?<Save size={11}/>:<Plus size={11}/>}Salvar</button><button onClick={reset} className="flex items-center justify-center gap-1 rounded border border-zinc-700 py-2 text-[10px] text-zinc-300"><X size={11}/>Cancelar</button></div></div><div className="mt-3 space-y-2">{tree.map(dep=><div key={dep.id} className="rounded-lg border border-zinc-800 bg-zinc-950/40 p-2"><div className="text-[10px] font-black uppercase tracking-wide text-blue-300">{dep.name}</div>{dep.sections.length===0&&<div className="mt-2 text-[9px] text-zinc-600">Nenhuma seção.</div>}{dep.sections.map((sec:any)=><div key={sec.id} className="ml-2 mt-2 border-l border-zinc-700 pl-2"><NodeRow node={sec} count={sec.categories.length} onEdit={edit} onDelete={remove}/>{sec.categories.map((cat:any)=><NodeRow key={cat.id} node={cat} count={(catalog.products as any[]).filter(p=>p.categoriaId===cat.id).length} nested onEdit={edit} onDelete={remove}/>)}</div>)}</div>)}</div></div></div>
}
function Header({message}:{message:string}){return <div className="border-b border-zinc-800 p-3"><div className="flex items-center gap-2"><FolderTree size={14} className="text-emerald-400"/><div><h3 className="text-xs font-bold text-zinc-100">Estrutura organizacional</h3><p className="text-[9px] text-zinc-500">Departamento → Seção → Categoria → Produto</p></div></div>{message&&<div className="mt-2 rounded border border-zinc-800 bg-zinc-950 p-2 text-[9px] text-zinc-300">{message}</div>}</div>}
function NodeRow({node,count,nested=false,onEdit,onDelete}:{node:any;count:number;nested?:boolean;onEdit:(n:any)=>void;onDelete:(n:any)=>void}){return <div className={`mt-1 flex items-center gap-1 rounded ${nested?'bg-zinc-900/70 px-2 py-1':'py-1'}`}><span className={`min-w-0 flex-1 truncate ${nested?'text-[9px] text-zinc-400':'text-[10px] font-semibold text-zinc-200'}`}>{node.name}</span><span className="text-[8px] text-zinc-600">{count}</span><button title="Editar" onClick={()=>onEdit(node)} className="p-1 text-zinc-600 hover:text-white"><Pencil size={9}/></button><button title="Excluir" onClick={()=>void onDelete(node)} className="p-1 text-zinc-600 hover:text-red-300"><Trash2 size={9}/></button></div>}
