import { useMemo, useState } from 'react';
import { BadgePercent, CheckSquare, Eye, Save, Settings2, Square, Trash2 } from 'lucide-react';
import { useCatalog } from '../catalog/store';
import { cloudApi, type CloudOffer } from './api';

const FIELD_OPTIONS=[
  ['image','Imagem'],['code','Código'],['shortDescription','Descrição'],['department','Departamento'],['section','Seção'],['category','Categoria'],['brand','Marca'],['price','Preço'],['unit','Unidade'],['stock','Estoque'],['ean','EAN'],['ncm','NCM'],['packaging','Embalagem'],['attributes','Outras informações'],
] as const;
const inputClass='w-full rounded-md border border-zinc-700 bg-zinc-950 px-2 py-1.5 text-[10px] text-zinc-200 outline-none focus:border-blue-500';

export function OffersPanel(){
  const catalog=useCatalog();
  const [tab,setTab]=useState<'offers'|'fields'>('offers');
  const [dep,setDep]=useState('');const [sec,setSec]=useState('');const [cat,setCat]=useState('');
  const [selected,setSelected]=useState<Set<string>>(new Set());const [editingId,setEditingId]=useState<string|null>(null);const [title,setTitle]=useState('Vitrine de Ofertas');const [description,setDescription]=useState('');const [status,setStatus]=useState<'draft'|'published'>('draft');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
  const [fields,setFields]=useState<string[]>(catalog.settings.displayFields);

  const activeHierarchy=catalog.hierarchy.filter((node:any)=>node.status!=='inactive');
  const departments=activeHierarchy.filter((node:any)=>node.level==='departamento'&&['Atacado','Distribuição'].includes(node.name));
  const sections=activeHierarchy.filter((node:any)=>node.level==='secao'&&(!dep||node.parentId===dep));
  const categories=activeHierarchy.filter((node:any)=>node.level==='categoria'&&(!sec||node.parentId===sec));
  const filtered=useMemo(()=>catalog.products.filter((product:any)=>(!dep||product.departamentoId===dep)&&(!sec||product.secaoId===sec)&&(!cat||product.categoriaId===cat)).sort((a:any,b:any)=>{const ca=catalog.hierarchy.find((n:any)=>n.id===a.categoriaId)?.name||'';const cb=catalog.hierarchy.find((n:any)=>n.id===b.categoriaId)?.name||'';return ca.localeCompare(cb,'pt-BR')||String(a.shortDescription).localeCompare(String(b.shortDescription),'pt-BR')}),[catalog.products,catalog.hierarchy,dep,sec,cat]);
  const offers=(catalog.promotions as any[]).map(item=>item as CloudOffer);
  const allFilteredSelected=filtered.length>0&&filtered.every(product=>selected.has(product.id));
  const toggle=(id:string)=>setSelected(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);return next});
  const toggleFiltered=()=>setSelected(prev=>{const next=new Set(prev);for(const product of filtered)allFilteredSelected?next.delete(product.id):next.add(product.id);return next});
  const reset=()=>{setEditingId(null);setTitle('Vitrine de Ofertas');setDescription('');setStatus('draft');setSelected(new Set());setMessage('')};
  const edit=(offer:CloudOffer)=>{setEditingId(offer.id);setTitle(offer.title||'Vitrine de Ofertas');setDescription(offer.description||'');setStatus(offer.status==='published'?'published':'draft');setSelected(new Set(offer.productIds||[]));setTab('offers')};
  const save=async()=>{if(!selected.size)return setMessage('Selecione pelo menos um produto para a vitrine.');setBusy(true);setMessage('Salvando vitrine...');try{await cloudApi.saveOffer({title:title.trim()||'Vitrine de Ofertas',description,status,productIds:Array.from(selected)},editingId||undefined);await catalog.reloadCatalog();setMessage('Vitrine salva no D1 com os produtos selecionados.');}catch(error){setMessage(error instanceof Error?error.message:'Falha ao salvar vitrine.')}finally{setBusy(false)}};
  const remove=async(id:string)=>{if(!window.confirm('Excluir esta vitrine de ofertas?'))return;setBusy(true);try{await cloudApi.deleteOffer(id);await catalog.reloadCatalog();if(editingId===id)reset()}catch(error){setMessage(error instanceof Error?error.message:'Falha ao excluir vitrine.')}finally{setBusy(false)}};
  const toggleField=(field:string)=>setFields(prev=>prev.includes(field)?prev.filter(item=>item!==field):[...prev,field]);
  const saveFields=async()=>{if(!fields.length)return setMessage('Mantenha pelo menos uma informação visível.');setBusy(true);try{await cloudApi.saveCatalogSettings(fields);await catalog.reloadCatalog();setMessage('Informações de exibição atualizadas.');}catch(error){setMessage(error instanceof Error?error.message:'Falha ao salvar configuração.')}finally{setBusy(false)}};

  return <div className="flex h-full flex-col bg-zinc-900">
    <div className="border-b border-zinc-800 p-3"><div className="flex items-center gap-2"><BadgePercent size={16} className="text-amber-400"/><div><h3 className="text-xs font-bold text-zinc-100">Ofertas e Vitrines</h3><p className="text-[9px] text-zinc-500">Selecione produtos sem misturar categorias e publique vitrines promocionais.</p></div></div><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>setTab('offers')} className={`rounded-md px-2 py-1.5 text-[10px] font-semibold ${tab==='offers'?'bg-blue-600 text-white':'bg-zinc-800 text-zinc-400'}`}>Vitrine de Ofertas</button><button onClick={()=>setTab('fields')} className={`rounded-md px-2 py-1.5 text-[10px] font-semibold ${tab==='fields'?'bg-blue-600 text-white':'bg-zinc-800 text-zinc-400'}`}>Dados exibidos</button></div>{message&&<div className="mt-2 rounded border border-zinc-800 bg-zinc-950 px-2 py-1.5 text-[9px] text-zinc-300">{message}</div>}</div>
    {tab==='fields'?<div className="flex-1 overflow-y-auto p-3"><div className="rounded-lg border border-zinc-800 bg-zinc-950/60 p-3"><div className="mb-2 flex items-center gap-2 text-[10px] font-bold uppercase text-zinc-300"><Settings2 size={12}/>Informações do produto</div><p className="mb-3 text-[9px] leading-relaxed text-zinc-500">Escolha quais campos aparecem no detalhe do produto e nas vitrines públicas.</p><div className="space-y-1.5">{FIELD_OPTIONS.map(([field,label])=><button key={field} onClick={()=>toggleField(field)} className="flex w-full items-center justify-between rounded border border-zinc-800 bg-zinc-900 px-2 py-2 text-left text-[10px] text-zinc-300"><span>{label}</span>{fields.includes(field)?<CheckSquare size={13} className="text-blue-400"/>:<Square size={13} className="text-zinc-600"/>}</button>)}</div><button disabled={busy} onClick={()=>void saveFields()} className="mt-3 flex w-full items-center justify-center gap-2 rounded-md bg-blue-600 py-2 text-[10px] font-bold text-white disabled:opacity-50"><Save size={12}/>Salvar configuração</button></div></div>:
    <div className="flex-1 overflow-y-auto p-3">
      <div className="rounded-lg border border-zinc-800 bg-zinc-950/55 p-3"><div className="grid grid-cols-3 gap-2"><label><span className="mb-1 block text-[9px] text-zinc-500">Departamento</span><select className={inputClass} value={dep} onChange={e=>{setDep(e.target.value);setSec('');setCat('')}}><option value="">Todos</option>{departments.map((node:any)=><option key={node.id} value={node.id}>{node.name}</option>)}</select></label><label><span className="mb-1 block text-[9px] text-zinc-500">Seção</span><select className={inputClass} value={sec} onChange={e=>{setSec(e.target.value);setCat('')}}><option value="">Todas</option>{sections.map((node:any)=><option key={node.id} value={node.id}>{node.name}</option>)}</select></label><label><span className="mb-1 block text-[9px] text-zinc-500">Categoria</span><select className={inputClass} value={cat} onChange={e=>setCat(e.target.value)}><option value="">Todas</option>{categories.map((node:any)=><option key={node.id} value={node.id}>{node.name}</option>)}</select></label></div><button onClick={toggleFiltered} className="mt-2 flex w-full items-center justify-center gap-2 rounded border border-zinc-700 bg-zinc-900 py-1.5 text-[9px] font-semibold text-zinc-300">{allFilteredSelected?<CheckSquare size={11}/>:<Square size={11}/>} {allFilteredSelected?'Desmarcar filtrados':'Selecionar todos filtrados'} ({filtered.length})</button></div>
      <div className="mt-3 space-y-1.5">{filtered.map((product:any)=>{const category=catalog.hierarchy.find((n:any)=>n.id===product.categoriaId)?.name||'Sem categoria';const brand=catalog.brandName(product.brandId);return <button key={product.id} onClick={()=>toggle(product.id)} className={`flex w-full items-center gap-2 rounded-lg border p-2 text-left ${selected.has(product.id)?'border-blue-500/50 bg-blue-500/10':'border-zinc-800 bg-zinc-950/55'}`}>{selected.has(product.id)?<CheckSquare size={14} className="shrink-0 text-blue-400"/>:<Square size={14} className="shrink-0 text-zinc-600"/>}{product.image?<img src={product.image} alt="" className="h-10 w-10 shrink-0 rounded bg-white object-contain"/>:<div className="grid h-10 w-10 shrink-0 place-items-center rounded bg-zinc-800 text-[8px] text-zinc-600">SEM IMG</div>}<div className="min-w-0 flex-1"><div className="truncate text-[10px] font-semibold text-zinc-200">{product.shortDescription}</div><div className="truncate text-[9px] text-zinc-500">{product.code} · {category} · {brand}</div></div></button>})}</div>
      <div className="mt-4 rounded-lg border border-zinc-800 bg-zinc-950/70 p-3"><div className="mb-2 flex items-center justify-between"><div className="text-[10px] font-bold uppercase text-amber-300">Vitrine de Ofertas</div><button onClick={reset} className="text-[9px] text-blue-400">Nova</button></div><input className={inputClass} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Nome da vitrine"/><textarea className={`${inputClass} mt-2 min-h-16 resize-y`} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Descrição da oferta"/><select className={`${inputClass} mt-2`} value={status} onChange={e=>setStatus(e.target.value as 'draft'|'published')}><option value="draft">Rascunho</option><option value="published">Publicada</option></select><div className="mt-2 text-[9px] text-zinc-500">{selected.size} produto(s) selecionado(s)</div><button disabled={busy} onClick={()=>void save()} className="mt-2 flex w-full items-center justify-center gap-2 rounded-md bg-amber-500 py-2 text-[10px] font-bold text-zinc-950 disabled:opacity-50"><Save size={12}/>{editingId?'Atualizar vitrine':'Criar vitrine'}</button></div>
      {offers.length>0&&<div className="mt-4"><div className="mb-2 text-[10px] font-bold uppercase text-zinc-400">Vitrines cadastradas</div><div className="space-y-2">{offers.map(offer=><div key={offer.id} className="rounded-lg border border-zinc-800 bg-zinc-950/55 p-2.5"><div className="flex items-start justify-between gap-2"><div><div className="text-[10px] font-semibold text-zinc-200">{offer.title}</div><div className="mt-1 text-[9px] text-zinc-500">{offer.productIds?.length||0} produto(s) · {offer.status==='published'?'Publicada':'Rascunho'}</div></div><div className="flex gap-1"><button title="Editar" onClick={()=>edit(offer)} className="rounded border border-zinc-700 p-1.5 text-zinc-400 hover:text-white"><Eye size={11}/></button><button title="Excluir" onClick={()=>void remove(offer.id)} className="rounded border border-zinc-700 p-1.5 text-zinc-400 hover:text-red-300"><Trash2 size={11}/></button></div></div></div>)}</div></div>}
    </div>}
  </div>
}
