import { audit, body, fail, ok, requireUser, uid, type Env } from './util';

function parseJson(v:any,fallback:any){try{return JSON.parse(v||'')}catch{return fallback}}
export async function catalogRoute(req:Request,env:Env,path:string){
  if(path==='/api/public/catalog'&&req.method==='GET')return catalog(env,true);
  if(path==='/api/admin/catalog'&&req.method==='GET'){const auth=await requireUser(req,env,['VIEWER','EDITOR','ADMIN']);if(auth.error)return auth.error;return catalog(env,false);}
  if(path==='/api/admin/catalog/products/bulk'&&req.method==='POST'){
    const auth=await requireUser(req,env,['EDITOR','ADMIN']);if(auth.error)return auth.error;const input=await body(req);const products=Array.isArray(input.products)?input.products.slice(0,5000):[];if(!products.length)return fail('Nenhum produto recebido');
    const importId=uid('imp');let inserted=0,updated=0,ignored=0;const existingRows=await env.DB.prepare("SELECT code FROM products WHERE company_id=?").bind(auth.user!.company_id).all();const existing=new Set((existingRows.results||[]).map((r:any)=>String(r.code)));
    const statements=[];for(const raw of products){const p=raw||{};const code=String(p.code??p.codigo??'').trim();const name=String(p.name??p.description??p.descricao??'').trim();if(!code||!name){ignored++;continue;}const data={...p,code,name};const status=['active','ativo'].includes(String(p.status||'').toLowerCase())?'active':'draft';if(existing.has(code))updated++;else{inserted++;existing.add(code);}statements.push(env.DB.prepare("INSERT INTO products (id,company_id,code,name,status,data_json,created_at,updated_at) VALUES (?,?,?,?,?,?,datetime('now'),datetime('now')) ON CONFLICT(company_id,code) DO UPDATE SET name=excluded.name,status=excluded.status,data_json=excluded.data_json,updated_at=datetime('now')").bind(uid('prd'),auth.user!.company_id,code,name,status,JSON.stringify(data)));}
    for(let i=0;i<statements.length;i+=100)await env.DB.batch(statements.slice(i,i+100));await env.DB.prepare("INSERT INTO imports (id,company_id,kind,filename,status,total_rows,inserted_rows,updated_rows,ignored_rows,error_rows,summary_json,finished_at) VALUES (?,?,?,?, 'completed',?,?,?,?,0,?,datetime('now'))").bind(importId,auth.user!.company_id,String(input.kind||'json'),String(input.filename||'importacao.json'),products.length,inserted,updated,ignored,JSON.stringify({source:'editor-v2.1'})).run();await audit(env,auth.user,'products.bulk','import',importId,{total:products.length,inserted,updated,ignored});return ok({importId,total:products.length,inserted,updated,ignored});
  }
  return null;
}

async function catalog(env:Env,publicOnly:boolean){const products=await env.DB.prepare(publicOnly?"SELECT * FROM products WHERE company_id='cmp_asteryon' AND status='active' ORDER BY updated_at DESC LIMIT 5000":"SELECT * FROM products WHERE company_id='cmp_asteryon' ORDER BY updated_at DESC LIMIT 5000").all();const brands=await env.DB.prepare("SELECT id,name,slug,status FROM brands WHERE company_id='cmp_asteryon' ORDER BY name").all();const distributions=await env.DB.prepare("SELECT id,name,slug,description,status FROM distributions WHERE company_id='cmp_asteryon' ORDER BY name").all();const hierarchy=await env.DB.prepare("SELECT id,name,slug,level,parent_id,sort_order,status FROM hierarchy_nodes WHERE company_id='cmp_asteryon' ORDER BY sort_order,name").all();const promotions=await env.DB.prepare(publicOnly?"SELECT * FROM promotions WHERE company_id='cmp_asteryon' AND status='published' AND (starts_at IS NULL OR starts_at<=datetime('now')) AND (ends_at IS NULL OR ends_at>=datetime('now')) ORDER BY featured DESC,updated_at DESC":"SELECT * FROM promotions WHERE company_id='cmp_asteryon' ORDER BY updated_at DESC").all();return ok({catalog:{products:(products.results||[]).map((r:any)=>({...parseJson(r.data_json,{}),id:r.id,code:r.code,name:r.name,status:r.status==='active'?'ativo':'rascunho'})),brands:brands.results||[],distributions:distributions.results||[],hierarchy:(hierarchy.results||[]).map((r:any)=>({...r,parentId:r.parent_id,sortOrder:r.sort_order})),promotions:(promotions.results||[]).map((r:any)=>({...parseJson(r.data_json,{}),id:r.id,title:r.title,description:r.description,status:r.status}))}})}
