import { audit, body, fail, ok, requireUser, uid, type Env } from './util';

const COMPANY_ID='cmp_asteryon';
const DEFAULT_MARKETING={
  banner:{active:false,mediaType:'image',mediaUrl:'',title:'',subtitle:'',link:'',autoplay:true,loop:true,muted:true},
  videoBanner:{active:false,mediaUrl:'',title:'',subtitle:'',autoplay:true,loop:true,muted:true,controls:false},
  carousel:{active:false,speed:1,loop:true,autoplay:true,manual:true,items:[]},
  theme:{mode:'light',primary:'#2563eb',secondary:'#f59e0b',background:'#ffffff',surface:'#f4f4f5',text:'#18181b'}
};

function clean(v:unknown){return String(v??'').trim()}
function slug(v:unknown){return clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function parse(v:any,fallback:any){try{return JSON.parse(v||'')}catch{return fallback}}
function num(v:any,fallback=0){const n=Number(v);return Number.isFinite(n)?n:fallback}
function status(v:any){return ['inactive','inativo','0','false'].includes(slug(v))?'inactive':'active'}
function website(v:any){const value=clean(v);if(!value)return '';if(/^https?:\/\//i.test(value))return value;return `https://${value.replace(/^\/+/, '')}`}
function mergeMarketing(input:any){
  const source=input&&typeof input==='object'?input:{};const banner={...DEFAULT_MARKETING.banner,...(source.banner||{})};const videoBanner={...DEFAULT_MARKETING.videoBanner,...(source.videoBanner||{})};const rawCarousel={...DEFAULT_MARKETING.carousel,...(source.carousel||{})};const items=Array.isArray(rawCarousel.items)?rawCarousel.items.slice(0,50).map((item:any)=>({id:clean(item.id)||uid('slide'),url:clean(item.url),link:clean(item.link),alt:clean(item.alt)})).filter((item:any)=>item.url):[];const speed=[1,1.5,2].includes(Number(rawCarousel.speed))?Number(rawCarousel.speed):1;const rawTheme={...DEFAULT_MARKETING.theme,...(source.theme||{})};const color=(v:any,fallback:string)=>/^#[0-9a-f]{6}$/i.test(clean(v))?clean(v):fallback;return{banner:{...banner,active:Boolean(banner.active),mediaType:banner.mediaType==='video'?'video':'image',mediaUrl:clean(banner.mediaUrl),title:clean(banner.title),subtitle:clean(banner.subtitle),link:clean(banner.link),autoplay:Boolean(banner.autoplay),loop:Boolean(banner.loop),muted:Boolean(banner.muted)},videoBanner:{...videoBanner,active:Boolean(videoBanner.active),mediaUrl:clean(videoBanner.mediaUrl),title:clean(videoBanner.title),subtitle:clean(videoBanner.subtitle),autoplay:Boolean(videoBanner.autoplay),loop:Boolean(videoBanner.loop),muted:Boolean(videoBanner.muted),controls:Boolean(videoBanner.controls)},carousel:{active:Boolean(rawCarousel.active),speed,loop:Boolean(rawCarousel.loop),autoplay:Boolean(rawCarousel.autoplay),manual:Boolean(rawCarousel.manual),items},theme:{mode:['light','dark','custom'].includes(clean(rawTheme.mode))?clean(rawTheme.mode):'light',primary:color(rawTheme.primary,DEFAULT_MARKETING.theme.primary),secondary:color(rawTheme.secondary,DEFAULT_MARKETING.theme.secondary),background:color(rawTheme.background,DEFAULT_MARKETING.theme.background),surface:color(rawTheme.surface,DEFAULT_MARKETING.theme.surface),text:color(rawTheme.text,DEFAULT_MARKETING.theme.text)}}
}
async function ensureSchema(env:Env){
  await env.DB.prepare("CREATE TABLE IF NOT EXISTS brand_profiles (brand_id TEXT PRIMARY KEY,company_id TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',logo_url TEXT,banner_url TEXT,website TEXT,sort_order INTEGER NOT NULL DEFAULT 0,featured INTEGER NOT NULL DEFAULT 0,data_json TEXT NOT NULL DEFAULT '{}',updated_at TEXT NOT NULL DEFAULT (datetime('now')))").run();
  await env.DB.prepare("CREATE TABLE IF NOT EXISTS marketing_settings (company_id TEXT PRIMARY KEY,config_json TEXT NOT NULL DEFAULT '{}',updated_at TEXT NOT NULL DEFAULT (datetime('now')))").run();
}

export async function managementRoute(req:Request,env:Env,path:string){
  await ensureSchema(env);
  if(path==='/api/public/brands'&&req.method==='GET')return ok({brands:await listBrands(env,true,COMPANY_ID)});
  if(path==='/api/public/marketing'&&req.method==='GET')return ok({marketing:await readMarketing(env,COMPANY_ID)});

  if(path==='/api/admin/brands'&&req.method==='GET'){const auth=await requireUser(req,env,['VIEWER','EDITOR','ADMIN']);if(auth.error)return auth.error;return ok({brands:await listBrands(env,false,auth.user!.company_id)});}
  if(path==='/api/admin/brands'&&req.method==='POST'){const auth=await requireUser(req,env,['EDITOR','ADMIN']);if(auth.error)return auth.error;return saveBrand(req,env,auth.user!,null);}
  if(path==='/api/admin/brands/bulk'&&req.method==='POST'){
    const auth=await requireUser(req,env,['EDITOR','ADMIN']);if(auth.error)return auth.error;const input=await body(req);const rows=Array.isArray(input.brands)?input.brands.slice(0,2000):[];if(!rows.length)return fail('Nenhuma marca recebida');let inserted=0,updated=0,ignored=0;const errors:string[]=[];
    for(let i=0;i<rows.length;i++){const row=rows[i]||{};const name=clean(row.name??row.marca);if(!name){ignored++;if(errors.length<20)errors.push(`Linha ${i+2}: nome da marca é obrigatório`);continue}const key=slug(name);const existing=await env.DB.prepare('SELECT id FROM brands WHERE company_id=? AND slug=? LIMIT 1').bind(auth.user!.company_id,key).first<any>();const id=String(existing?.id||uid('brd'));if(existing)updated++;else inserted++;await env.DB.prepare("INSERT INTO brands (id,company_id,name,slug,status,updated_at) VALUES (?,?,?,?,?,datetime('now')) ON CONFLICT(company_id,slug) DO UPDATE SET name=excluded.name,status=excluded.status,updated_at=datetime('now')").bind(id,auth.user!.company_id,name,key,status(row.status)).run();const actual=await env.DB.prepare('SELECT id FROM brands WHERE company_id=? AND slug=? LIMIT 1').bind(auth.user!.company_id,key).first<any>();const brandId=String(actual?.id||id);await upsertProfile(env,auth.user!.company_id,brandId,row);}
    await audit(env,auth.user,'brands.bulk','brand',null,{inserted,updated,ignored,errors});return ok({inserted,updated,ignored,errors,brands:await listBrands(env,false,auth.user!.company_id)});
  }
  const brandMatch=path.match(/^\/api\/admin\/brands\/([^/]+)$/);
  if(brandMatch&&req.method==='PUT'){const auth=await requireUser(req,env,['EDITOR','ADMIN']);if(auth.error)return auth.error;return saveBrand(req,env,auth.user!,decodeURIComponent(brandMatch[1]));}
  if(brandMatch&&req.method==='DELETE'){
    const auth=await requireUser(req,env,['ADMIN']);if(auth.error)return auth.error;const id=decodeURIComponent(brandMatch[1]);const found=await env.DB.prepare('SELECT id,name FROM brands WHERE id=? AND company_id=?').bind(id,auth.user!.company_id).first<any>();if(!found)return fail('Marca não encontrada',404,'NOT_FOUND');const products=await env.DB.prepare('SELECT id,data_json FROM products WHERE company_id=? AND brand_id=?').bind(auth.user!.company_id,id).all();for(const row of products.results||[]){const data=parse((row as any).data_json,{});data.brandId=null;data.brandName='';await env.DB.prepare("UPDATE products SET brand_id=NULL,data_json=?,updated_at=datetime('now') WHERE id=?").bind(JSON.stringify(data),(row as any).id).run();}await env.DB.prepare('DELETE FROM brand_profiles WHERE brand_id=? AND company_id=?').bind(id,auth.user!.company_id).run();await env.DB.prepare('DELETE FROM brands WHERE id=? AND company_id=?').bind(id,auth.user!.company_id).run();await deleteEntityMedia(env,auth.user!.company_id,['brand-logo','brand-banner'],id);await audit(env,auth.user,'brand.delete','brand',id,{name:found.name,unlinkedProducts:(products.results||[]).length});return ok({id});
  }

  if(path==='/api/admin/hierarchy'&&req.method==='POST'){const auth=await requireUser(req,env,['EDITOR','ADMIN']);if(auth.error)return auth.error;return saveHierarchy(req,env,auth.user!,null);}
  const hierarchyMatch=path.match(/^\/api\/admin\/hierarchy\/([^/]+)$/);
  if(hierarchyMatch&&req.method==='PUT'){const auth=await requireUser(req,env,['EDITOR','ADMIN']);if(auth.error)return auth.error;return saveHierarchy(req,env,auth.user!,decodeURIComponent(hierarchyMatch[1]));}
  if(hierarchyMatch&&req.method==='DELETE'){
    const auth=await requireUser(req,env,['ADMIN']);if(auth.error)return auth.error;const id=decodeURIComponent(hierarchyMatch[1]);const node=await env.DB.prepare('SELECT id,name,level FROM hierarchy_nodes WHERE id=? AND company_id=?').bind(id,auth.user!.company_id).first<any>();if(!node)return fail('Item da estrutura não encontrado',404,'NOT_FOUND');if(node.level==='departamento')return fail('Os departamentos Atacado e Distribuição são fixos e não podem ser excluídos',409,'FIXED_DEPARTMENT');const children=await env.DB.prepare('SELECT COUNT(*) c FROM hierarchy_nodes WHERE company_id=? AND parent_id=?').bind(auth.user!.company_id,id).first<any>();if(Number(children?.c||0)>0)return fail('Existem itens abaixo desta estrutura. Reclassifique ou exclua-os primeiro.',409,'HAS_CHILDREN');if(node.level==='categoria'){const products=await env.DB.prepare('SELECT COUNT(*) c FROM products WHERE company_id=? AND category_id=?').bind(auth.user!.company_id,id).first<any>();if(Number(products?.c||0)>0)return fail('Existem produtos nesta categoria. Reclassifique-os antes de excluir.',409,'HAS_PRODUCTS');}await env.DB.prepare('DELETE FROM hierarchy_nodes WHERE id=? AND company_id=?').bind(id,auth.user!.company_id).run();await audit(env,auth.user,'hierarchy.delete','hierarchy',id,{name:node.name,level:node.level});return ok({id});
  }

  const productMatch=path.match(/^\/api\/admin\/products\/([^/]+)$/);
  if(productMatch&&req.method==='PUT'){
    const auth=await requireUser(req,env,['EDITOR','ADMIN']);if(auth.error)return auth.error;const id=decodeURIComponent(productMatch[1]);const input=await body(req);const row=await env.DB.prepare('SELECT id,code,data_json FROM products WHERE id=? AND company_id=?').bind(id,auth.user!.company_id).first<any>();if(!row)return fail('Produto não encontrado',404,'NOT_FOUND');const data=parse(row.data_json,{});if(input.status!==undefined){const active=status(input.status)==='active';data.status=active?'ativo':'inativo';await env.DB.prepare("UPDATE products SET status=?,data_json=?,updated_at=datetime('now') WHERE id=? AND company_id=?").bind(active?'active':'draft',JSON.stringify(data),id,auth.user!.company_id).run();await audit(env,auth.user,'product.status','product',id,{code:row.code,status:active?'active':'inactive'});return ok({id,status:active?'active':'inactive'});}return fail('Nenhuma alteração válida informada');
  }
  if(productMatch&&req.method==='DELETE'){
    const auth=await requireUser(req,env,['ADMIN']);if(auth.error)return auth.error;const id=decodeURIComponent(productMatch[1]);const row=await env.DB.prepare('SELECT id,code FROM products WHERE id=? AND company_id=?').bind(id,auth.user!.company_id).first<any>();if(!row)return fail('Produto não encontrado',404,'NOT_FOUND');await env.DB.prepare('DELETE FROM promotion_products WHERE product_id=?').bind(id).run();await env.DB.prepare('DELETE FROM products WHERE id=? AND company_id=?').bind(id,auth.user!.company_id).run();await deleteEntityMedia(env,auth.user!.company_id,['product-image','product-video'],String(row.code));await audit(env,auth.user,'product.delete','product',id,{code:row.code});return ok({id,code:row.code});
  }

  if(path==='/api/admin/marketing'&&req.method==='GET'){const auth=await requireUser(req,env,['VIEWER','EDITOR','ADMIN']);if(auth.error)return auth.error;return ok({marketing:await readMarketing(env,auth.user!.company_id)});}
  if(path==='/api/admin/marketing'&&req.method==='PUT'){
    const auth=await requireUser(req,env,['EDITOR','ADMIN']);if(auth.error)return auth.error;const input=await body(req);const marketing=mergeMarketing(input.marketing??input);await env.DB.prepare("INSERT INTO marketing_settings (company_id,config_json,updated_at) VALUES (?,?,datetime('now')) ON CONFLICT(company_id) DO UPDATE SET config_json=excluded.config_json,updated_at=datetime('now')").bind(auth.user!.company_id,JSON.stringify(marketing)).run();await audit(env,auth.user,'marketing.save','marketing',auth.user!.company_id,{banner:marketing.banner.active,video:marketing.videoBanner.active,carousel:marketing.carousel.active,slides:marketing.carousel.items.length,theme:marketing.theme.mode});return ok({marketing});
  }
  return null;
}

async function saveBrand(req:Request,env:Env,user:any,id:string|null){
  const input=await body(req);const name=clean(input.name);if(!name)return fail('Nome da marca é obrigatório');const key=slug(name);if(!key)return fail('Nome da marca inválido');if(id){const found=await env.DB.prepare('SELECT id,name FROM brands WHERE id=? AND company_id=?').bind(id,user.company_id).first<any>();if(!found)return fail('Marca não encontrada',404,'NOT_FOUND');const duplicate=await env.DB.prepare('SELECT id FROM brands WHERE company_id=? AND slug=? AND id<>? LIMIT 1').bind(user.company_id,key,id).first<any>();if(duplicate)return fail('Já existe uma marca com este nome',409,'DUPLICATE');await env.DB.prepare("UPDATE brands SET name=?,slug=?,status=?,updated_at=datetime('now') WHERE id=? AND company_id=?").bind(name,key,status(input.status),id,user.company_id).run();await upsertProfile(env,user.company_id,id,input);await updateBrandNameOnProducts(env,user.company_id,id,name);await audit(env,user,'brand.update','brand',id,{name,status:status(input.status)});return ok({brand:(await listBrands(env,false,user.company_id)).find((b:any)=>b.id===id)});}const existing=await env.DB.prepare('SELECT id FROM brands WHERE company_id=? AND slug=? LIMIT 1').bind(user.company_id,key).first<any>();if(existing)return fail('Já existe uma marca com este nome',409,'DUPLICATE');const brandId=uid('brd');await env.DB.prepare("INSERT INTO brands (id,company_id,name,slug,status) VALUES (?,?,?,?,?)").bind(brandId,user.company_id,name,key,status(input.status)).run();await upsertProfile(env,user.company_id,brandId,input);await audit(env,user,'brand.create','brand',brandId,{name});return ok({brand:(await listBrands(env,false,user.company_id)).find((b:any)=>b.id===brandId)});
}
async function upsertProfile(env:Env,companyId:string,brandId:string,input:any){const description=clean(input.description);const logoUrl=clean(input.logoUrl??input.logo_url)||null;const bannerUrl=clean(input.bannerUrl??input.banner_url)||null;const site=website(input.website??input.site)||null;const sortOrder=Math.max(0,Math.floor(num(input.sortOrder??input.ordem,0)));const featured=Boolean(input.featured);const data={launches:Array.isArray(input.launches)?input.launches:[],featuredProductIds:Array.isArray(input.featuredProductIds)?input.featuredProductIds:[],catalogUrl:clean(input.catalogUrl)};await env.DB.prepare("INSERT INTO brand_profiles (brand_id,company_id,description,logo_url,banner_url,website,sort_order,featured,data_json,updated_at) VALUES (?,?,?,?,?,?,?,?,?,datetime('now')) ON CONFLICT(brand_id) DO UPDATE SET description=excluded.description,logo_url=excluded.logo_url,banner_url=excluded.banner_url,website=excluded.website,sort_order=excluded.sort_order,featured=excluded.featured,data_json=excluded.data_json,updated_at=datetime('now')").bind(brandId,companyId,description,logoUrl,bannerUrl,site,sortOrder,featured?1:0,JSON.stringify(data)).run();}
async function listBrands(env:Env,publicOnly:boolean,companyId:string){const sql=`SELECT b.id,b.name,b.slug,b.status,p.description,p.logo_url,p.banner_url,p.website,p.sort_order,p.featured,p.data_json FROM brands b LEFT JOIN brand_profiles p ON p.brand_id=b.id AND p.company_id=b.company_id WHERE b.company_id=? ${publicOnly?"AND b.status='active'":''} ORDER BY COALESCE(p.sort_order,0),b.name`;const rows=await env.DB.prepare(sql).bind(companyId).all();return (rows.results||[]).map((r:any)=>({...parse(r.data_json,{}),id:r.id,name:r.name,slug:r.slug,status:r.status,description:r.description||'',logoUrl:r.logo_url||'',bannerUrl:r.banner_url||'',website:r.website||'',sortOrder:Number(r.sort_order||0),featured:Boolean(r.featured)}));}
async function updateBrandNameOnProducts(env:Env,companyId:string,brandId:string,name:string){const rows=await env.DB.prepare('SELECT id,data_json FROM products WHERE company_id=? AND brand_id=?').bind(companyId,brandId).all();for(const row of rows.results||[]){const data=parse((row as any).data_json,{});data.brandId=brandId;data.brandName=name;await env.DB.prepare("UPDATE products SET data_json=?,updated_at=datetime('now') WHERE id=?").bind(JSON.stringify(data),(row as any).id).run();}}

async function saveHierarchy(req:Request,env:Env,user:any,id:string|null){const input=await body(req);const name=clean(input.name);if(!name)return fail('Nome é obrigatório');if(id){const node=await env.DB.prepare('SELECT id,level,parent_id FROM hierarchy_nodes WHERE id=? AND company_id=?').bind(id,user.company_id).first<any>();if(!node)return fail('Item da estrutura não encontrado',404,'NOT_FOUND');if(node.level==='departamento'&&!['Atacado','Distribuição'].includes(name))return fail('Os departamentos permitidos são Atacado e Distribuição',409,'FIXED_DEPARTMENT');const storageSlug=node.level==='departamento'?slug(name):`${slug(node.parent_id||'root')}--${slug(name)}`;await env.DB.prepare("UPDATE hierarchy_nodes SET name=?,slug=?,sort_order=?,status=?,updated_at=datetime('now') WHERE id=? AND company_id=?").bind(name,storageSlug,Math.floor(num(input.sortOrder,0)),status(input.status),id,user.company_id).run();await audit(env,user,'hierarchy.update','hierarchy',id,{name,level:node.level});return ok({id});}const level=clean(input.level);if(!['secao','categoria'].includes(level))return fail('Só é permitido criar Seção ou Categoria. Departamentos são fixos.');const parentId=clean(input.parentId);if(!parentId)return fail('Selecione o item superior');const parent=await env.DB.prepare('SELECT id,name,level FROM hierarchy_nodes WHERE id=? AND company_id=?').bind(parentId,user.company_id).first<any>();if(!parent)return fail('Item superior não encontrado');if(level==='secao'&&(parent.level!=='departamento'||!['Atacado','Distribuição'].includes(parent.name)))return fail('Seção deve pertencer a Atacado ou Distribuição');if(level==='categoria'&&parent.level!=='secao')return fail('Categoria deve pertencer a uma Seção');const duplicate=await env.DB.prepare('SELECT id FROM hierarchy_nodes WHERE company_id=? AND level=? AND parent_id=? AND name=? LIMIT 1').bind(user.company_id,level,parentId,name).first<any>();if(duplicate)return fail('Já existe um item com este nome nesta estrutura',409,'DUPLICATE');const nodeId=uid('hier');const storageSlug=`${slug(parent.name)}--${slug(name)}`;await env.DB.prepare("INSERT INTO hierarchy_nodes (id,company_id,name,slug,level,parent_id,sort_order,status) VALUES (?,?,?,?,?,?,?,'active')").bind(nodeId,user.company_id,name,storageSlug,level,parentId,Math.floor(num(input.sortOrder,100))).run();await audit(env,user,'hierarchy.create','hierarchy',nodeId,{name,level,parentId});return ok({id:nodeId});}

async function readMarketing(env:Env,companyId:string){const row=await env.DB.prepare('SELECT config_json FROM marketing_settings WHERE company_id=?').bind(companyId).first<any>();return mergeMarketing(parse(row?.config_json,DEFAULT_MARKETING));}
async function deleteEntityMedia(env:Env,companyId:string,kinds:string[],entityKey:string){for(const kind of kinds){const rows=await env.DB.prepare('SELECT media_key FROM media_objects WHERE company_id=? AND kind=? AND entity_key=?').bind(companyId,kind,entityKey).all();for(const row of rows.results||[]){const key=String((row as any).media_key);await env.DB.prepare('DELETE FROM media_chunks WHERE media_key=?').bind(key).run();await env.DB.prepare('DELETE FROM media_objects WHERE media_key=?').bind(key).run();}}}
