import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import { BRANDS, COMPANY, DISTRIBUTIONS, HIERARCHY, PRODUCTS, PROMOTIONS } from './seed';
import type { Brand, Distribution, HierarchyNode, Product, Promotion } from './types';
import { cloudApi, isCloudRuntime, type CatalogSettings } from '../cloud/api';

const DEFAULT_SETTINGS:CatalogSettings={displayFields:['image','code','shortDescription','brand','category','price','unit']};
interface CatalogState {products:Product[];brands:Brand[];distributions:Distribution[];hierarchy:HierarchyNode[];promotions:Promotion[];settings:CatalogSettings;}
interface CatalogContextValue extends CatalogState {productById:(id?:string|null)=>Product|undefined;brandName:(id?:string|null)=>string;distributionName:(id?:string|null)=>string;hierarchyPath:(product:Product)=>string[];searchProducts:(query:string)=>Product[];setProducts:React.Dispatch<React.SetStateAction<Product[]>>;cloudLoading:boolean;cloudError:string|null;reloadCatalog:()=>Promise<void>;}
const CatalogContext=createContext<CatalogContextValue|null>(null);
const clean=(value:unknown)=>String(value||'').trim();
const slug=(value:unknown)=>clean(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');

function normalizeCatalog(input:{products:Product[];brands:Brand[];distributions:Distribution[];hierarchy:HierarchyNode[];promotions:Promotion[];settings?:CatalogSettings}){
  const brands=[...(input.brands||[])];const hierarchy=[...(input.hierarchy||[])];const brandBySlug=new Map(brands.map(brand=>[slug(brand.name),brand]));const nodeByKey=new Map(hierarchy.map(node=>[`${node.level}:${String(node.parentId||'')}:${slug(node.name)}`,node]));
  const ensureBrand=(name:string)=>{if(!name)return null;const key=slug(name);let brand=brandBySlug.get(key);if(!brand){brand={id:`auto_brand_${key}`,companyId:COMPANY.id,name,slug:key} as Brand;brands.push(brand);brandBySlug.set(key,brand)}return brand.id};
  const ensureNode=(level:HierarchyNode['level'],name:string,parentId:string|null)=>{if(!name)return null;const key=`${level}:${String(parentId||'')}:${slug(name)}`;let node=nodeByKey.get(key);if(!node){node={id:`auto_${level}_${slug(parentId||'root')}_${slug(name)}`,companyId:COMPANY.id,name,level,parentId} as HierarchyNode;hierarchy.push(node);nodeByKey.set(key,node)}return node.id};
  const products=(input.products||[]).map(product=>{const raw=product as Product&Record<string,any>;const brandId=product.brandId||ensureBrand(clean(raw.brandName));const departamentoId=product.departamentoId||ensureNode('departamento',clean(raw.departamentoName),null);const secaoId=product.secaoId||ensureNode('secao',clean(raw.secaoName),departamentoId);const categoriaId=product.categoriaId||ensureNode('categoria',clean(raw.categoriaName),secaoId||departamentoId);const subcategoriaId=product.subcategoriaId||ensureNode('subcategoria',clean(raw.subcategoriaName),categoriaId);return{...product,brandId,departamentoId,secaoId,categoriaId,subcategoriaId,technical:{...(product.technical||{}),...(raw.ncm?{NCM:clean(raw.ncm)}:{})}}});
  return{products,brands,distributions:input.distributions||[],hierarchy,promotions:input.promotions||[],settings:input.settings||DEFAULT_SETTINGS};
}

export function CatalogProvider({children}:{children:ReactNode}){
  const [products,setProducts]=useState<Product[]>(PRODUCTS);const [brands,setBrands]=useState<Brand[]>(BRANDS);const [distributions,setDistributions]=useState<Distribution[]>(DISTRIBUTIONS);const [hierarchy,setHierarchy]=useState<HierarchyNode[]>(HIERARCHY);const [promotions,setPromotions]=useState<Promotion[]>(PROMOTIONS);const [settings,setSettings]=useState<CatalogSettings>(DEFAULT_SETTINGS);const [cloudLoading,setCloudLoading]=useState(isCloudRuntime());const [cloudError,setCloudError]=useState<string|null>(null);
  const reloadCatalog=async()=>{if(!isCloudRuntime())return;setCloudLoading(true);try{const result=await cloudApi.getCatalog(false);const normalized=normalizeCatalog(result.catalog as any);setProducts(normalized.products);setBrands(normalized.brands);setDistributions(normalized.distributions);setHierarchy(normalized.hierarchy);setPromotions(normalized.promotions);setSettings(normalized.settings);setCloudError(null)}catch(error){setCloudError(error instanceof Error?error.message:'Falha ao carregar catálogo do D1')}finally{setCloudLoading(false)}};
  useEffect(()=>{void reloadCatalog()},[]);
  const value=useMemo<CatalogContextValue>(()=>({products,brands,distributions,hierarchy,promotions,settings,productById:(id)=>products.find(p=>p.id===id),brandName:(id)=>brands.find(b=>b.id===id)?.name??'Sem marca',distributionName:(id)=>distributions.find(d=>d.id===id)?.name??'Sem distribuição',hierarchyPath:(product)=>[product.departamentoId,product.secaoId,product.categoriaId].map(id=>hierarchy.find(n=>n.id===id)?.name).filter((v):v is string=>Boolean(v)),searchProducts:(query)=>{const q=query.trim().toLowerCase();if(!q)return products;return products.filter(p=>{const raw=p as Product&Record<string,any>;const brand=brands.find(b=>b.id===p.brandId)?.name??'';const dist=distributions.find(d=>d.id===p.distributionId)?.name??'';const hier=[p.departamentoId,p.secaoId,p.categoriaId].map(id=>hierarchy.find(n=>n.id===id)?.name??'').join(' ');return[p.code,p.ean,raw.ncm,p.technical?.NCM,p.packaging,p.shortDescription,p.longDescription,brand,dist,hier,p.tags.join(' ')].join(' ').toLowerCase().includes(q)});},setProducts,cloudLoading,cloudError,reloadCatalog}),[products,brands,distributions,hierarchy,promotions,settings,cloudLoading,cloudError]);
  return <CatalogContext.Provider value={value}>{children}</CatalogContext.Provider>;
}
export function useCatalog(){const ctx=useContext(CatalogContext);if(!ctx)throw new Error('useCatalog deve ser usado dentro de CatalogProvider');return ctx}
export function brl(value:number){return value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
export {COMPANY};
