import React, {useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as XLSX from 'xlsx';
import {Search,Menu,Eye,Save,Upload,Image as ImageIcon,BarChart3,LayoutDashboard,Package,Tags,Percent,Palette,LogOut,ChevronRight,Plus,Trash2,Monitor,Tablet,Smartphone,CheckCircle2,X,FileSpreadsheet,FolderTree,Megaphone,Settings,ExternalLink} from 'lucide-react';
import './styles.css';

const seedProducts=[
 {code:'10001',name:'Chocolate ao Leite 80g',brand:'Lacta',department:'Alimentos',category:'Bomboniere',section:'Chocolates',subcategory:'Barras',price:'5,99',showPrice:true,image:'https://images.unsplash.com/photo-1575377427642-087cf684f29d?auto=format&fit=crop&w=500&q=80',details:{code:true,brand:true,ean:false,department:true,description:true}},
 {code:'10002',name:'Café Tradicional 500g',brand:'3 Corações',department:'Alimentos',category:'Mercearia',section:'Cafés',subcategory:'Tradicional',price:'27,98',showPrice:true,image:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=500&q=80',details:{code:true,brand:true,ean:false,department:false,description:true}},
 {code:'10003',name:'Cerveja Long Neck 330ml',brand:'Heineken',department:'Bebidas',category:'Cervejas',section:'Pilsen',subcategory:'Long Neck',price:'4,49',showPrice:true,image:'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=500&q=80',details:{code:true,brand:true,ean:false,department:true,description:true}},
 {code:'10004',name:'Amaciante Tradicional 1,7L',brand:'Comfort',department:'Limpeza',category:'Lavanderia',section:'Amaciantes',subcategory:'Tradicional',price:'14,39',showPrice:false,image:'https://images.unsplash.com/photo-1585421514284-efb74c2b69ba?auto=format&fit=crop&w=500&q=80',details:{code:true,brand:true,ean:false,department:true,description:true}},
 {code:'10005',name:'Arroz Branco 5kg',brand:'Tio João',department:'Alimentos',category:'Mercearia',section:'Arroz',subcategory:'Branco',price:'24,99',showPrice:true,image:'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=500&q=80',details:{code:true,brand:true,ean:false,department:false,description:true}},
 {code:'10006',name:'Detergente Neutro 500ml',brand:'Ypê',department:'Limpeza',category:'Cozinha',section:'Detergentes',subcategory:'Neutro',price:'1,79',showPrice:true,image:'https://images.unsplash.com/photo-1583947581924-860bda6a26df?auto=format&fit=crop&w=500&q=80',details:{code:true,brand:true,ean:false,department:true,description:true}}
];
const defaultConfig={brand:'SuaMarca',primary:'#0d5b2a',secondary:'#1d7a3b',background:'#f6f7f8',card:'#ffffff',text:'#1b2430',font:'Inter, system-ui, sans-serif',bannerTitle:'Ofertas que cabem no seu negócio!',bannerSubtitle:'Produtos em destaque e campanhas personalizadas.',bannerCta:'Aproveitar ofertas',theme:'Padrão',seasonFx:true};
const defaultPromos=[{id:'p1',name:'Ofertas da Semana',products:['10001','10003','10005'],active:true}];

function useStore(){
 const [products,setProducts]=useState(()=>JSON.parse(localStorage.getItem('ac_products')||'null')||seedProducts);
 const [published,setPublished]=useState(()=>JSON.parse(localStorage.getItem('ac_published')||'null')||defaultConfig);
 const [draft,setDraft]=useState(()=>JSON.parse(localStorage.getItem('ac_draft')||'null')||defaultConfig);
 const [promos,setPromos]=useState(()=>JSON.parse(localStorage.getItem('ac_promos')||'null')||defaultPromos);
 const [analytics,setAnalytics]=useState(()=>JSON.parse(localStorage.getItem('ac_analytics')||'null')||{views:{},searches:{},departments:{},promotions:{}});
 useEffect(()=>localStorage.setItem('ac_products',JSON.stringify(products)),[products]);
 useEffect(()=>localStorage.setItem('ac_published',JSON.stringify(published)),[published]);
 useEffect(()=>localStorage.setItem('ac_draft',JSON.stringify(draft)),[draft]);
 useEffect(()=>localStorage.setItem('ac_promos',JSON.stringify(promos)),[promos]);
 useEffect(()=>localStorage.setItem('ac_analytics',JSON.stringify(analytics)),[analytics]);
 return {products,setProducts,published,setPublished,draft,setDraft,promos,setPromos,analytics,setAnalytics};
}

function track(setAnalytics,type,key){setAnalytics(a=>({...a,[type]:{...(a[type]||{}),[key]:((a[type]||{})[key]||0)+1}}));}
function money(v){return v?`R$ ${v}`:''}

function SeasonalFx({theme,enabled}){if(!enabled||theme==='Padrão')return null;return <div className={'season-fx '+theme.toLowerCase().replace(/\s/g,'-')} aria-hidden>{Array.from({length:18}).map((_,i)=><span key={i} style={{left:`${(i*37)%100}%`,animationDelay:`${(i%7)*.4}s`}}>{theme==='Natal'?'❄':theme==='Carnaval'?'◆':theme==='Ano Novo'?'✦':theme==='Black Friday'?'●':theme==='Dia das Mães'?'✿':theme==='Dia dos Pais'?'★':'●'}</span>)}</div>}

function PublicPortal({store,preview=false,configOverride}){
 const {products,published,promos,setAnalytics}=store; const cfg=configOverride||published;
 const [q,setQ]=useState(''); const [selected,setSelected]=useState(null); const [dept,setDept]=useState('Todos');
 const departments=['Todos',...new Set(products.map(p=>p.department))];
 const filtered=products.filter(p=>(dept==='Todos'||p.department===dept)&&([p.name,p.brand,p.code,p.department,p.category,p.section,p.subcategory].join(' ').toLowerCase().includes(q.toLowerCase())));
 const onSearch=v=>{setQ(v);if(v.trim().length>=2)track(setAnalytics,'searches',v.trim().toLowerCase())};
 return <div className="portal" style={{'--primary':cfg.primary,'--secondary':cfg.secondary,'--bg':cfg.background,'--card':cfg.card,'--text':cfg.text,fontFamily:cfg.font}}>
  <SeasonalFx theme={cfg.theme} enabled={cfg.seasonFx}/>
  {preview&&<div className="preview-badge">PRÉ-VISUALIZAÇÃO — não publicado</div>}
  <header className="public-header"><div className="brand">◈ <strong>{cfg.brand}</strong></div><div className="searchbox"><Search size={18}/><input value={q} onChange={e=>onSearch(e.target.value)} placeholder="Buscar produtos, marcas, categorias..."/></div><nav><a href="#promo">Promoções</a><a href="#catalogo">Catálogo</a></nav></header>
  <div className="deptbar">{departments.map(d=><button key={d} className={dept===d?'active':''} onClick={()=>{setDept(d); if(d!=='Todos')track(setAnalytics,'departments',d)}}>{d}</button>)}</div>
  <main>
   <section className="hero"><div><small>{cfg.theme!=='Padrão'?`Tema ${cfg.theme} ativo`:'CATÁLOGO DIGITAL'}</small><h1>{cfg.bannerTitle}</h1><p>{cfg.bannerSubtitle}</p><button>{cfg.bannerCta}</button></div><div className="hero-orb">OFERTAS<br/><b>EM DESTAQUE</b></div></section>
   <section className="quick"><div>✓ Catálogo organizado</div><div>⚡ Pesquisa inteligente</div><div>▦ Encartes e promoções</div><div>↗ Atualização rápida</div></section>
   <section id="promo"><div className="section-head"><h2>Promoções</h2><span>Produtos de diferentes categorias podem ser misturados aqui</span></div>{promos.filter(x=>x.active).map(pr=><div key={pr.id}><h3 className="promo-title" onClick={()=>track(setAnalytics,'promotions',pr.name)}>{pr.name}</h3><div className="grid">{products.filter(p=>pr.products.includes(p.code)).map(p=><ProductCard key={p.code} p={p} onOpen={()=>{setSelected(p);track(setAnalytics,'views',p.code)}}/>)}</div></div>)}</section>
   <section id="catalogo"><div className="section-head"><h2>{dept==='Todos'?'Catálogo completo':dept}</h2><span>{filtered.length} produtos</span></div><div className="grid">{filtered.map(p=><ProductCard key={p.code} p={p} onOpen={()=>{setSelected(p);track(setAnalytics,'views',p.code)}}/>)}</div></section>
  </main>
  <footer>© {new Date().getFullYear()} {cfg.brand} • Catálogo digital</footer>
  {selected&&<ProductModal p={selected} onClose={()=>setSelected(null)}/>} 
 </div>
}
function ProductCard({p,onOpen}){return <article className="product-card"><div className="product-image"><img src={p.image} alt=""/></div><button className="product-title" onClick={onOpen}>{p.name}</button><div className="crumb">{p.department} › {p.category} › {p.section}</div><div className="brandline">{p.brand}</div>{p.showPrice&&<strong className="price">{money(p.price)}</strong>}<button className="details" onClick={onOpen}>Ver informações</button></article>}
function ProductModal({p,onClose}){const d=p.details||{};return <div className="modal-back" onClick={onClose}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X/></button><img src={p.image}/><div><h2>{p.name}</h2>{d.brand!==false&&<p><b>Marca:</b> {p.brand}</p>}{d.code!==false&&<p><b>Código:</b> {p.code}</p>}{d.department&&<p><b>Localização:</b> {p.department} › {p.category} › {p.section} › {p.subcategory}</p>}{p.showPrice&&<h3>{money(p.price)}</h3>}<p>As informações exibidas nesta ficha são configuráveis pelo administrador.</p></div></div></div>}

function AdminApp({store}){const [logged,setLogged]=useState(()=>localStorage.getItem('ac_admin')==='1'); const [page,setPage]=useState('Dashboard');
 if(!logged)return <Login onLogin={()=>{localStorage.setItem('ac_admin','1');setLogged(true)}}/>;
 const menu=[['Dashboard',LayoutDashboard],['Editor Visual',Palette],['Produtos',Package],['Estrutura',FolderTree],['Promoções',Percent],['Importações',Upload],['Analytics',BarChart3],['Configurações',Settings]];
 return <div className="admin-shell"><aside><div className="admin-logo">◈ ASTERYON<small>CATÁLOGO ADMIN</small></div>{menu.map(([n,I])=><button className={page===n?'active':''} onClick={()=>setPage(n)} key={n}><I size={18}/>{n}</button>)}<button onClick={()=>{localStorage.removeItem('ac_admin');setLogged(false)}}><LogOut size={18}/>Sair</button></aside><section className="admin-main"><AdminTop title={page}/>{page==='Dashboard'&&<Dashboard store={store}/>} {page==='Editor Visual'&&<VisualEditor store={store}/>} {page==='Produtos'&&<ProductsAdmin store={store}/>} {page==='Estrutura'&&<StructureAdmin store={store}/>} {page==='Promoções'&&<PromotionsAdmin store={store}/>} {page==='Importações'&&<ImportsAdmin store={store}/>} {page==='Analytics'&&<Analytics store={store}/>} {page==='Configurações'&&<SettingsAdmin store={store}/>}</section></div>}
function Login({onLogin}){const [email,setEmail]=useState('admin@empresa.com.br'),[pass,setPass]=useState('demo123');return <div className="login"><div className="login-card"><div className="login-mark">◈</div><h1>ASTERYON</h1><p>Painel Administrativo</p><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Senha<input type="password" value={pass} onChange={e=>setPass(e.target.value)}/></label><button onClick={onLogin}>Entrar no modo demonstração</button><small>Protótipo local. Em produção, substituir por Supabase Auth.</small></div></div>}
function AdminTop({title}){return <div className="admin-top"><div><h1>{title}</h1><p>Painel de gestão do catálogo</p></div><a href="/" target="_blank"><Eye size={17}/> Ver portal público</a></div>}
function Dashboard({store}){const {analytics,products,promos}=store;const views=Object.values(analytics.views||{}).reduce((a,b)=>a+b,0), searches=Object.values(analytics.searches||{}).reduce((a,b)=>a+b,0);return <div className="pad"><div className="metrics"><Metric n={views} t="Visualizações de produtos"/><Metric n={searches} t="Pesquisas"/><Metric n={products.length} t="Produtos cadastrados"/><Metric n={promos.length} t="Promoções"/></div><div className="two"><Panel title="Produtos mais acessados"><Ranking obj={analytics.views} labels={Object.fromEntries(products.map(p=>[p.code,p.name]))}/></Panel><Panel title="Pesquisas mais realizadas"><Ranking obj={analytics.searches}/></Panel></div><div className="notice"><CheckCircle2/> O portal público continua exibindo somente a última versão publicada. Alterações do editor ficam em rascunho até você publicar.</div></div>}
function Metric({n,t}){return <div className="metric"><strong>{n.toLocaleString('pt-BR')}</strong><span>{t}</span></div>}
function Panel({title,children}){return <div className="panel"><h3>{title}</h3>{children}</div>}
function Ranking({obj={},labels={}}){const rows=Object.entries(obj).sort((a,b)=>b[1]-a[1]).slice(0,8);return rows.length?<ol className="ranking">{rows.map(([k,v])=><li key={k}><span>{labels[k]||k}</span><b>{v}</b></li>)}</ol>:<p className="muted">Ainda não há dados. Navegue no portal para gerar acessos.</p>}

function VisualEditor({store}){const {draft,setDraft,published,setPublished}=store; const [device,setDevice]=useState('desktop'); const update=(k,v)=>setDraft(d=>({...d,[k]:v})); return <div className="editor-layout"><div className="editor-toolbar"><div className="device"><button onClick={()=>setDevice('desktop')} className={device==='desktop'?'active':''}><Monitor size={17}/></button><button onClick={()=>setDevice('tablet')} className={device==='tablet'?'active':''}><Tablet size={17}/></button><button onClick={()=>setDevice('mobile')} className={device==='mobile'?'active':''}><Smartphone size={17}/></button></div><button className="ghost" onClick={()=>setDraft(published)}><Trash2 size={16}/>Descartar rascunho</button><button className="publish" onClick={()=>{setPublished(draft);alert('Alterações publicadas no portal.')}}><CheckCircle2 size={16}/>Publicar alterações</button></div><div className="editor-body"><div className={'preview-frame '+device}><PublicPortal store={store} preview configOverride={draft}/></div><aside className="props"><h3>Propriedades</h3><label>Nome/Logo<input value={draft.brand} onChange={e=>update('brand',e.target.value)}/></label><label>Cor principal<input type="color" value={draft.primary} onChange={e=>update('primary',e.target.value)}/></label><label>Cor secundária<input type="color" value={draft.secondary} onChange={e=>update('secondary',e.target.value)}/></label><label>Fundo<input type="color" value={draft.background} onChange={e=>update('background',e.target.value)}/></label><label>Cor dos cards<input type="color" value={draft.card} onChange={e=>update('card',e.target.value)}/></label><label>Título do banner<input value={draft.bannerTitle} onChange={e=>update('bannerTitle',e.target.value)}/></label><label>Subtítulo<textarea value={draft.bannerSubtitle} onChange={e=>update('bannerSubtitle',e.target.value)}/></label><label>Botão<input value={draft.bannerCta} onChange={e=>update('bannerCta',e.target.value)}/></label><label>Tema<select value={draft.theme} onChange={e=>update('theme',e.target.value)}>{['Padrão','Natal','Black Friday','Dia das Mães','Dia dos Pais','Dia das Crianças','Ano Novo','Carnaval'].map(x=><option key={x}>{x}</option>)}</select></label><label className="switch"><input type="checkbox" checked={draft.seasonFx} onChange={e=>update('seasonFx',e.target.checked)}/> Animações sazonais</label><div className="status"><b>Rascunho separado do público</b><small>O portal só muda ao clicar em “Publicar alterações”.</small></div></aside></div></div>}

function ProductsAdmin({store}){const {products,setProducts}=store;const [selected,setSelected]=useState(products[0]);const upd=(k,v)=>{setProducts(ps=>ps.map(p=>p.code===selected.code?{...p,[k]:v}:p));setSelected(s=>({...s,[k]:v}))};return <div className="pad"><div className="page-actions"><button onClick={()=>{const code=String(Date.now()).slice(-6);const p={code,name:'Novo produto',brand:'',department:'Alimentos',category:'Nova categoria',section:'Nova seção',subcategory:'',price:'',showPrice:false,image:'',details:{code:true,brand:true,department:true,description:true}};setProducts([...products,p]);setSelected(p)}}><Plus size={16}/>Novo produto</button></div><div className="product-admin"><div className="table-wrap"><table><thead><tr><th>Código</th><th>Produto</th><th>Departamento</th><th>Categoria</th><th>Preço</th></tr></thead><tbody>{products.map(p=><tr key={p.code} onClick={()=>setSelected(p)} className={selected?.code===p.code?'sel':''}><td>{p.code}</td><td>{p.name}</td><td>{p.department}</td><td>{p.category}</td><td>{p.showPrice?money(p.price):'Oculto'}</td></tr>)}</tbody></table></div>{selected&&<div className="form-card"><h3>Editar produto</h3>{['code','name','brand','department','category','section','subcategory','price'].map(k=><label key={k}>{({code:'Código',name:'Descrição',brand:'Marca',department:'Departamento',category:'Categoria',section:'Seção',subcategory:'Subcategoria',price:'Preço (opcional)'})[k]}<input value={selected[k]||''} onChange={e=>upd(k,e.target.value)}/></label>)}<label className="switch"><input type="checkbox" checked={selected.showPrice} onChange={e=>upd('showPrice',e.target.checked)}/> Exibir preço</label><p className="muted">Na navegação normal, o produto segue obrigatoriamente Departamento › Categoria › Seção › Subcategoria. Apenas Promoções podem misturar produtos.</p></div>}</div></div>}

function StructureAdmin({store}){const {products}=store;const tree=useMemo(()=>{const root={};products.forEach(p=>{root[p.department]??={};root[p.department][p.category]??={};root[p.department][p.category][p.section]??=new Set();root[p.department][p.category][p.section].add(p.subcategory||'Sem subcategoria')});return root},[products]);return <div className="pad"><Panel title="Árvore do catálogo"><p className="muted">A estrutura aceita subníveis. Distribuições podem ser mantidas como árvore adicional sem duplicar produtos.</p><div className="tree">{Object.entries(tree).map(([d,cats])=><div key={d}><b>▾ {d}</b>{Object.entries(cats).map(([c,secs])=><div className="l2" key={c}>↳ {c}{Object.entries(secs).map(([s,subs])=><div className="l3" key={s}>↳ {s}<div className="l4">{[...subs].map(x=><span key={x}>• {x}</span>)}</div></div>)}</div>)}</div>)}</div></Panel></div>}

function PromotionsAdmin({store}){const {products,promos,setPromos}=store;const [name,setName]=useState('Nova promoção');const create=()=>setPromos([...promos,{id:'p'+Date.now(),name,products:[],active:true}]);const toggle=(id,code)=>setPromos(ps=>ps.map(p=>p.id===id?{...p,products:p.products.includes(code)?p.products.filter(x=>x!==code):[...p.products,code]}:p));return <div className="pad"><div className="page-actions"><input value={name} onChange={e=>setName(e.target.value)}/><button onClick={create}><Plus size={16}/>Criar promoção</button></div>{promos.map(pr=><Panel key={pr.id} title={pr.name}><p className="muted">Promoções podem misturar livremente produtos de departamentos, categorias e seções diferentes.</p><div className="check-grid">{products.map(p=><label key={p.code}><input type="checkbox" checked={pr.products.includes(p.code)} onChange={()=>toggle(pr.id,p.code)}/>{p.name}<small>{p.department} › {p.category}</small></label>)}</div></Panel>)}</div>}

function ImportsAdmin({store}){const {products,setProducts}=store;const [report,setReport]=useState(null);async function importSheet(file){const buf=await file.arrayBuffer();const wb=XLSX.read(buf);const rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});let created=0,updated=0;setProducts(prev=>{let next=[...prev];rows.forEach(r=>{const code=String(r.Codigo||r.CÓDIGO||r.CODIGO||r.codigo||r.codprod||r.CODPROD||'').trim();if(!code)return;const data={code,name:r.Descricao||r.DESCRICAO||r.descricao||r.Produto||r.PRODUTO||`Produto ${code}`,brand:r.Marca||r.MARCA||r.marca||'',department:r.Departamento||r.DEPARTAMENTO||r.Depto||r.DEPTO||'Sem departamento',category:r.Categoria||r.CATEGORIA||r.categoria||'Sem categoria',section:r.Secao||r.SECAO||r.Seção||r.SEÇÃO||'Sem seção',subcategory:r.Subcategoria||r.SUBCATEGORIA||'',price:String(r.Preco||r.PRECO||r.Preço||r.PREÇO||''),showPrice:false,image:'',details:{code:true,brand:true,department:true,description:true}};const idx=next.findIndex(p=>p.code===code);if(idx>=0){next[idx]={...next[idx],...data,image:next[idx].image};updated++}else{next.push(data);created++}});return next});setReport({type:'Planilha',created,updated,total:rows.length})}
 async function importImages(files){let linked=0,unlinked=0;const updates={};for(const file of files){const base=file.name.replace(/\.[^.]+$/,'');const code=base.split(/[_-]/)[0];if(!products.some(p=>p.code===code)){unlinked++;continue}const data=await new Promise(res=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.readAsDataURL(file)});updates[code]=data;linked++}setProducts(ps=>ps.map(p=>updates[p.code]?{...p,image:updates[p.code]}:p));setReport({type:'Imagens',linked,unlinked,total:files.length})}
 return <div className="pad"><div className="two"><Panel title="Importar produtos Excel/CSV"><div className="drop"><FileSpreadsheet size={40}/><b>Envie .xlsx, .xls ou .csv</b><p>O código da planilha é preservado como código do produto.</p><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>e.target.files[0]&&importSheet(e.target.files[0])}/></div></Panel><Panel title="Importar imagens"><div className="drop"><ImageIcon size={40}/><b>PNG/JPG pelo código do produto</b><p>Ex.: 10001.png, 10001_2.png. O vínculo é automático pelo nome do arquivo.</p><input type="file" accept="image/png,image/jpeg" multiple onChange={e=>importImages([...e.target.files])}/></div></Panel></div>{report&&<div className="report"><CheckCircle2/><div><b>Importação concluída: {report.type}</b><pre>{JSON.stringify(report,null,2)}</pre></div></div>}</div>}

function Analytics({store}){const {analytics,products}=store;return <div className="pad"><div className="metrics"><Metric n={Object.values(analytics.views||{}).reduce((a,b)=>a+b,0)} t="Aberturas de produtos"/><Metric n={Object.values(analytics.searches||{}).reduce((a,b)=>a+b,0)} t="Pesquisas"/><Metric n={Object.values(analytics.departments||{}).reduce((a,b)=>a+b,0)} t="Acessos a departamentos"/><Metric n={Object.values(analytics.promotions||{}).reduce((a,b)=>a+b,0)} t="Acessos a promoções"/></div><div className="two"><Panel title="Produtos"><Ranking obj={analytics.views} labels={Object.fromEntries(products.map(p=>[p.code,p.name]))}/></Panel><Panel title="Departamentos"><Ranking obj={analytics.departments}/></Panel><Panel title="Pesquisas"><Ranking obj={analytics.searches}/></Panel><Panel title="Promoções"><Ranking obj={analytics.promotions}/></Panel></div></div>}
function SettingsAdmin(){return <div className="pad"><Panel title="Arquitetura de produção"><ul className="spec"><li><b>Portal público:</b> www.empresa.com.br</li><li><b>Administrador:</b> admin.empresa.com.br</li><li><b>Banco:</b> Supabase PostgreSQL + Storage</li><li><b>Deploy:</b> GitHub → Cloudflare</li><li><b>Publicação:</b> rascunho separado da versão pública</li><li><b>Segurança:</b> Supabase Auth, RLS, rate limiting, logs e auditoria</li></ul></Panel></div>}

function App(){const store=useStore(); const isAdmin=location.hostname.startsWith('admin.')||location.pathname.startsWith('/admin');return isAdmin?<AdminApp store={store}/>:<PublicPortal store={store}/>}
createRoot(document.getElementById('root')).render(<App/>);
