import{useEffect,useMemo,useState,type CSSProperties,type ReactNode}from'react';
import{X}from'lucide-react';
import type{DeviceType,EditorNode}from'../editor/types';
import{getResponsiveRect}from'../editor/utils';
import{renderContent,styleObj}from'../editor/nodeContent';
import{cloudApi,type CatalogSettings,type CloudOffer}from'../cloud/api';
import{executeNodeAction,inferAnchorId,resolveNodeAction}from'../cloud/buttonActions';
import{DEFAULT_MARKETING,productionApi,type BrandProfile,type MarketingConfig}from'../cloud/productionApi';
import{PublicMarketingV3}from'./PublicMarketingV3';
import{BrandPageV3,CatalogMenuV3,OfferShowcasesV3,OrganizedCatalogV3,ProductModalV3,ProductPageV3,type CatalogProduct}from'./PublicCatalogV3';

const DEFAULT_FIELDS=['image','code','shortDescription','brand','category','price','unit'];
export function PublicSiteV3(){
  const[nodes,setNodes]=useState<EditorNode[]>([]),[products,setProducts]=useState<CatalogProduct[]>([]),[brands,setBrands]=useState<BrandProfile[]>([]),[hierarchy,setHierarchy]=useState<any[]>([]),[promotions,setPromotions]=useState<CloudOffer[]>([]),[settings,setSettings]=useState<CatalogSettings>({displayFields:DEFAULT_FIELDS}),[marketing,setMarketing]=useState<MarketingConfig>(DEFAULT_MARKETING),[selected,setSelected]=useState<CatalogProduct|null>(null),[notice,setNotice]=useState(''),[custom,setCustom]=useState<any|null>(null),[error,setError]=useState('');
  const{viewport,device}=usePublicDevice();
  useEffect(()=>{Promise.all([cloudApi.publicPage('home'),cloudApi.getCatalog(true),productionApi.listBrands(true),productionApi.getMarketing(true)]).then(([page,catalog,brandData,marketingData])=>{setNodes(page.page.nodes);setProducts(catalog.catalog.products as any[]);setBrands(brandData.brands);setHierarchy(catalog.catalog.hierarchy);setPromotions((catalog.catalog.promotions||[]) as any);setSettings(catalog.catalog.settings||{displayFields:DEFAULT_FIELDS});setMarketing(marketingData);document.title=page.page.title||'ASTERYON'}).catch(reason=>setError(reason instanceof Error?reason.message:'Site ainda não publicado'))},[]);
  useEffect(()=>{const noticeHandler=(event:Event)=>{const detail=(event as CustomEvent).detail;setNotice(String(detail?.message||''));window.setTimeout(()=>setNotice(''),3200)},customHandler=(event:Event)=>setCustom((event as CustomEvent).detail||{});window.addEventListener('asteryon:notice',noticeHandler);window.addEventListener('asteryon:custom-action',customHandler);return()=>{window.removeEventListener('asteryon:notice',noticeHandler);window.removeEventListener('asteryon:custom-action',customHandler)}},[]);
  const productMap=useMemo(()=>new Map(products.map(product=>[String(product.id),product])),[products]),brandMap=useMemo(()=>new Map(brands.map(brand=>[brand.id,brand.name])),[brands]);
  const page=nodes.find(node=>node.type==='page');const theme=marketing.theme||DEFAULT_MARKETING.theme;const route=decodeURIComponent(window.location.pathname),productMatch=route.match(/^\/produto\/([^/]+)\/?$/),brandMatch=route.match(/^\/marca\/([^/]+)\/?$/);const routeProduct=productMatch?products.find(product=>String(product.id)===productMatch[1]||String(product.code)===productMatch[1])||null:null,routeBrand=brandMatch?brands.find(brand=>brand.id===brandMatch[1]||brand.slug===brandMatch[1])||null:null;
  if(!page)return <Loading error={error} theme={theme}/>;
  if(productMatch)return <ProductPageV3 product={routeProduct} products={products} brands={brands} hierarchy={hierarchy} promotions={promotions} settings={settings} theme={theme}/>;
  if(brandMatch)return <BrandPageV3 brand={routeBrand} products={products} brands={brands} hierarchy={hierarchy} promotions={promotions} settings={settings} theme={theme}/>;
  return <main id="topo" data-catalog-anchor="topo" style={{background:theme.background,color:theme.text,minHeight:'100vh',overflowX:'hidden'}}><CatalogMenuV3 products={products} hierarchy={hierarchy} theme={theme}/><PublicMarketingV3 config={marketing}/><ResponsiveCanvas page={page} viewport={viewport} device={device}>{(page.children??[]).filter(node=>node.visible).map(node=><NodeView key={node.id} node={node} device={device} productMap={productMap} brandMap={brandMap} onProduct={setSelected}/>)}</ResponsiveCanvas><OrganizedCatalogV3 products={products} brands={brands} hierarchy={hierarchy} settings={settings} onProduct={setSelected} theme={theme}/><OfferShowcasesV3 offers={promotions} products={products} brands={brands} hierarchy={hierarchy} settings={settings} onProduct={setSelected} theme={theme}/>{selected&&<ProductModalV3 product={selected} brands={brands} hierarchy={hierarchy} settings={settings} onClose={()=>setSelected(null)} theme={theme}/>} {notice&&<div className="fixed bottom-4 left-1/2 z-[1000000] -translate-x-1/2 rounded-full bg-zinc-950 px-4 py-2 text-sm font-bold text-white shadow-2xl">{notice}</div>}{custom&&<CustomModal detail={custom} onClose={()=>setCustom(null)} theme={theme}/>}</main>
}
function usePublicDevice(){
  const[viewport,setViewport]=useState(()=>typeof window==='undefined'?1440:window.innerWidth);
  useEffect(()=>{const resize=()=>setViewport(window.innerWidth);window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize)},[]);
  const device:DeviceType=viewport<=767?'mobile':viewport<=1100?'tablet':'desktop';
  return{viewport,device};
}
function ResponsiveCanvas({page,viewport,device,children}:{page:EditorNode;viewport:number;device:DeviceType;children:ReactNode}){
  const rect=getResponsiveRect(page,device);
  const scale=Math.min(1,viewport/Math.max(1,rect.width));
  return <div data-public-device={device} data-design-width={rect.width} style={{height:rect.height*scale,width:'100%',overflow:'hidden'}}>
    <div style={{position:'relative',width:rect.width,height:rect.height,transform:`scale(${scale})`,transformOrigin:'top left',background:String(page.styles.backgroundColor||'transparent')}}>{children}</div>
  </div>
}
function NodeView({node,device,productMap,brandMap,onProduct}:{node:EditorNode;device:DeviceType;productMap:Map<string,CatalogProduct>;brandMap:Map<string,string>;onProduct:(product:CatalogProduct)=>void}){
  const initial=resolveNodeAction(node),candidate=String(node.props?.productId||(initial.context==='product'?initial.value:'')||''),product=productMap.get(candidate),live=product?liveProductNode(node,product,brandMap):node,action=resolveNodeAction(live),actionProduct=productMap.get(String(action.value||live.props?.productId||'')),infoProduct=product||actionProduct,isInfo=(live.type==='productbutton'||live.type==='button')&&action.type==='product-info'&&Boolean(infoProduct),isAction=(live.type==='button'||live.type==='productbutton')&&action.type!=='none',anchor=inferAnchorId(live),anchorId=anchor&&(live.children?.length??0)>0?anchor:undefined,rect=getResponsiveRect(live,device),box:CSSProperties={position:'absolute',left:rect.x,top:rect.y,width:rect.width,height:rect.height,zIndex:live.zIndex,opacity:live.opacity,transform:`rotate(${live.rotation||0}deg)`,cursor:isAction?'pointer':undefined};
  const run=()=>{if(isInfo&&infoProduct){onProduct(infoProduct);return}executeNodeAction(live)};
  return <div id={anchorId} data-catalog-anchor={anchorId} data-responsive-device={device} data-node-id={live.id} style={box} role={isAction?'button':undefined} tabIndex={isAction?0:undefined} onClick={isAction?(event)=>{event.stopPropagation();run()}:undefined} onKeyDown={isAction?(event)=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();run()}}:undefined}><div style={styleObj(live)}>{renderContent(live,false)}{(live.children??[]).filter(child=>child.visible).map(child=><NodeView key={child.id} node={child} device={device} productMap={productMap} brandMap={brandMap} onProduct={onProduct}/>)}</div></div>
}
function liveProductNode(node:EditorNode,product:CatalogProduct,brandMap:Map<string,string>):EditorNode{const props={...(node.props||{})};if(node.type==='productimage')props.src=product.image||'';if(node.type==='productbrand')props.text=brandMap.get(String(product.brandId||''))||product.brandName||'Sem marca';if(node.type==='productname')props.text=product.shortDescription||product.name;if(node.type==='productprice')props.text=displayPrice(product);return{...node,props}}
function displayPrice(product:any){if(product.priceMode==='oculto')return'';if(product.priceMode==='consulte')return'Consulte';if(product.priceMode==='sob_consulta')return'Sob consulta';if(product.priceMode==='loja')return'Disponível na loja';const value=product.promoPrice??product.price;return typeof value==='number'?value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'Consulte'}
function Loading({error,theme}:{error:string;theme:MarketingConfig['theme']}){return <div className="grid min-h-screen place-items-center p-6" style={{background:theme.background,color:theme.text}}><div className="rounded-2xl p-8 text-center shadow" style={{background:theme.surface}}><h1 className="text-xl font-bold">ASTERYON</h1><p className="mt-2 text-sm opacity-60">{error||'Carregando catálogo...'}</p>{error&&<a className="mt-4 inline-block rounded-lg px-4 py-2 text-sm font-bold text-white" style={{background:theme.primary}} href="/admin">Abrir Editor</a>}</div></div>}
function CustomModal({detail,onClose,theme}:{detail:any;onClose:()=>void;theme:MarketingConfig['theme']}){return <div className="fixed inset-0 z-[999999] grid place-items-center bg-black/60 p-4" onClick={onClose}><div className="w-full max-w-lg rounded-2xl p-6 shadow-2xl" style={{background:theme.surface,color:theme.text}} onClick={event=>event.stopPropagation()}><div className="flex items-center justify-between"><h2 className="text-xl font-black">{detail.title||'Atendimento'}</h2><button onClick={onClose}><X size={18}/></button></div><p className="mt-3 whitespace-pre-wrap text-sm opacity-70">{detail.message||'Ação aberta pelo elemento configurado no editor.'}</p>{detail.value&&<div className="mt-3 rounded-lg p-3 text-sm" style={{background:theme.background}}>{String(detail.value)}</div>}</div></div>}
